using Npgsql;
using PostgreManagementStudio.Application;

namespace PostgreManagementStudio.Postgres;

public sealed class NpgsqlDataTransferService
{
    public async Task<ImportResult> ImportAsync(string connectionString, ImportRequest request, IProgress<ImportProgress>? progress = null, CancellationToken cancellationToken = default)
    {
        ImportMappingService.Validate(request.Mappings, request.DestinationColumns); var started = DateTimeOffset.UtcNow; var errors = new List<string>(); long read = 0, written = 0, rejected = 0; var builder = new NpgsqlConnectionStringBuilder(connectionString) { ApplicationName = "PostgreManagementStudio - Data Import" }; await using var connection = new NpgsqlConnection(builder.ConnectionString); await connection.OpenAsync(cancellationToken); await using var transaction = request.Options.Transaction == TransactionMode.AllRows ? await connection.BeginTransactionAsync(cancellationToken) : null;
        try { if (request.Options.ExistingData == ExistingDataMode.Truncate) await ExecutePrep(connection, transaction, $"TRUNCATE TABLE {PostgreSqlIdentifierQuoter.Qualified(request.Schema, request.Table)}", cancellationToken); else if (request.Options.ExistingData == ExistingDataMode.Delete) await ExecutePrep(connection, transaction, $"DELETE FROM {PostgreSqlIdentifierQuoter.Qualified(request.Schema, request.Table)}", cancellationToken); var mappings = request.Mappings.Where(x => x.Included && x.DestinationName is not null).ToArray(); var columns = string.Join(",", mappings.Select(x => PostgreSqlIdentifierQuoter.Quote(x.DestinationName!))); var rows = new DelimitedFileReader().Read(request.SourcePath, request.FileSettings, cancellationToken); if (request.Options.Strategy == ImportStrategy.Copy) { await using var importer = await connection.BeginBinaryImportAsync($"COPY {PostgreSqlIdentifierQuoter.Qualified(request.Schema, request.Table)} ({columns}) FROM STDIN (FORMAT BINARY)", cancellationToken); foreach (var fields in rows) { read++; try { await importer.StartRowAsync(cancellationToken); foreach (var map in mappings) { var destination = request.DestinationColumns.Single(x => x.Name == map.DestinationName); await importer.WriteAsync(DataValueConverter.Convert(fields[map.SourceOrdinal], destination.PostgreSqlType, request.FileSettings), cancellationToken); } written++; } catch (Exception ex) { rejected++; errors.Add($"Row {read}: {ex.Message}"); if (errors.Count >= request.Options.ErrorLimit) break; } progress?.Report(new(read, written, rejected, "Importing")); } await importer.CompleteAsync(cancellationToken); } else { foreach (var fields in rows) { read++; try { await Insert(connection, transaction, request, mappings, fields, cancellationToken); written++; } catch (Exception ex) { rejected++; errors.Add($"Row {read}: {ex.Message}"); if (!request.Options.ContinueOnError || errors.Count >= request.Options.ErrorLimit) break; } progress?.Report(new(read, written, rejected, "Importing")); } } if (transaction is not null) await transaction.CommitAsync(cancellationToken); return new(rejected == 0 ? "Completed" : "Completed with rejected rows", read, written, rejected, DateTimeOffset.UtcNow - started, errors); } catch (OperationCanceledException) { if (transaction is not null) await transaction.RollbackAsync(); return new("Cancelled", read, written, rejected, DateTimeOffset.UtcNow - started, errors); } catch { if (transaction is not null) await transaction.RollbackAsync(); throw; }
    }
    private static async Task Insert(NpgsqlConnection connection, NpgsqlTransaction? transaction, ImportRequest request, ColumnMapping[] mappings, string[] fields, CancellationToken token) { var names = string.Join(",", mappings.Select(x => PostgreSqlIdentifierQuoter.Quote(x.DestinationName!))); var parameters = string.Join(",", mappings.Select((_, i) => "@v" + i)); await using var command = new NpgsqlCommand($"INSERT INTO {PostgreSqlIdentifierQuoter.Qualified(request.Schema, request.Table)} ({names}) VALUES ({parameters})", connection, transaction); for (var i = 0; i < mappings.Length; i++) { var destination = request.DestinationColumns.Single(x => x.Name == mappings[i].DestinationName); command.Parameters.AddWithValue("v" + i, DataValueConverter.Convert(fields[mappings[i].SourceOrdinal], destination.PostgreSqlType, request.FileSettings) ?? DBNull.Value); } await command.ExecuteNonQueryAsync(token); }
    private static async Task ExecutePrep(NpgsqlConnection c, NpgsqlTransaction? t, string sql, CancellationToken token) { await using var command = new NpgsqlCommand(sql, c, t); await command.ExecuteNonQueryAsync(token); }
}
