using Npgsql;
using PostgreManagementStudio.Core;

namespace PostgreManagementStudio.Postgres;

public sealed class NpgsqlMetadataProvider : IPostgresMetadataProvider
{
    public async Task<DatabaseMetadataSnapshot> LoadAsync(string connectionString, string database, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(connectionString); await connection.OpenAsync(cancellationToken); var schemas = await ReadStrings(connection, "SELECT nspname FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema' ORDER BY nspname", cancellationToken); var relations = new List<RelationMetadata>(); await using (var command = new NpgsqlCommand("SELECT n.nspname, c.relname, c.relkind FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p','v','m','S') AND n.nspname NOT LIKE 'pg_%' ORDER BY n.nspname,c.relname", connection)) await using (var reader = await command.ExecuteReaderAsync(cancellationToken)) { while (await reader.ReadAsync(cancellationToken)) relations.Add(new(reader.GetString(0), reader.GetString(1), reader.GetChar(2) switch { 'v' => CompletionKind.View, 'm' => CompletionKind.MaterializedView, 'S' => CompletionKind.Sequence, _ => CompletionKind.Table }, Array.Empty<ColumnMetadata>())); }
        await using (var command = new NpgsqlCommand("SELECT n.nspname, p.proname, pg_get_function_result(p.oid), pg_get_function_identity_arguments(p.oid), CASE WHEN p.prokind='p' THEN 'procedure' ELSE 'function' END FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname NOT LIKE 'pg_%' ORDER BY n.nspname,p.proname", connection)) await using (var reader = await command.ExecuteReaderAsync(cancellationToken)) { while (await reader.ReadAsync(cancellationToken)) { var kind = reader.GetString(4) == "procedure" ? CompletionKind.Procedure : CompletionKind.Function; } }
        var columns = new List<(string schema, string relation, ColumnMetadata column)>(); await using (var command = new NpgsqlCommand("SELECT n.nspname,c.relname,a.attname,format_type(a.atttypid,a.atttypmod),a.attnum,(NOT a.attnotnull) FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE a.attnum>0 AND NOT a.attisdropped AND c.relkind IN ('r','p','v','m') ORDER BY n.nspname,c.relname,a.attnum", connection)) await using (var reader = await command.ExecuteReaderAsync(cancellationToken)) while (await reader.ReadAsync(cancellationToken)) columns.Add((reader.GetString(0), reader.GetString(1), new(reader.GetString(2), reader.GetString(3), reader.GetInt16(4), reader.GetBoolean(5)))); relations = relations.Select(r => r with { Columns = columns.Where(c => c.schema == r.SchemaName && c.relation == r.Name).Select(c => c.column).ToArray() }).ToList(); return new(connectionString.GetHashCode().ToString(), database, schemas, relations, Array.Empty<RoutineMetadata>(), Array.Empty<string>(), relations.Where(r => r.Kind == CompletionKind.Sequence).Select(r => r.Name).ToArray(), DateTimeOffset.UtcNow);
    }
    private static async Task<IReadOnlyList<string>> ReadStrings(NpgsqlConnection connection, string sql, CancellationToken token) { var result = new List<string>(); await using var command = new NpgsqlCommand(sql, connection); await using var reader = await command.ExecuteReaderAsync(token); while (await reader.ReadAsync(token)) result.Add(reader.GetString(0)); return result; }
}
