using Npgsql;
using PostgreManagementStudio.Application;

namespace PostgreManagementStudio.Postgres;

public sealed class NpgsqlSessionManagementService
{
    public async Task<SessionActionResult> CancelAsync(string connectionString, SessionIdentity expected, int currentPid, int? monitoringPid, CancellationToken cancellationToken = default) => await ActAsync(connectionString, expected, currentPid, monitoringPid, false, cancellationToken);
    public async Task<SessionActionResult> TerminateAsync(string connectionString, SessionIdentity expected, int currentPid, int? monitoringPid, CancellationToken cancellationToken = default) => await ActAsync(connectionString, expected, currentPid, monitoringPid, true, cancellationToken);
    public async Task<IReadOnlyList<SessionActionResult>> ExecuteBulkAsync(string connectionString, IReadOnlyList<(SessionIdentity Identity, bool Terminate)> targets, int currentPid, int? monitoringPid, CancellationToken cancellationToken = default)
    { var results = new List<SessionActionResult>(); foreach (var target in targets.GroupBy(x => x.Identity.ProcessId).Select(x => x.First())) { results.Add(target.Terminate ? await TerminateAsync(connectionString, target.Identity, currentPid, monitoringPid, cancellationToken) : await CancelAsync(connectionString, target.Identity, currentPid, monitoringPid, cancellationToken)); } return results; }
    private static async Task<SessionActionResult> ActAsync(string cs, SessionIdentity expected, int currentPid, int? monitoringPid, bool terminate, CancellationToken token)
    { var action = terminate ? "terminate" : "cancel"; var safety = expected.ProcessId == currentPid ? new BackendActionResult(false, "self", "The current application session is protected.") : expected.ProcessId == monitoringPid ? new BackendActionResult(false, "monitoring-session", "The monitoring session is protected.") : new BackendActionResult(true, "eligible", ""); if (!safety.Accepted) return new(action, expected.ProcessId, false, safety.Code, safety.Message); try { await using var connection = new NpgsqlConnection(cs); await connection.OpenAsync(token); await using (var identity = new NpgsqlCommand("SELECT pid,backend_start,datname,usename,application_name FROM pg_stat_activity WHERE pid=@pid", connection)) { identity.Parameters.AddWithValue("pid", expected.ProcessId); await using var reader = await identity.ExecuteReaderAsync(token); if (!await reader.ReadAsync(token)) return new(action, expected.ProcessId, false, "stale-pid", "The original backend no longer exists."); var current = new SessionIdentity(reader.GetInt32(0), reader.IsDBNull(1) ? null : reader.GetFieldValue<DateTimeOffset>(1), reader.IsDBNull(2) ? null : reader.GetString(2), reader.IsDBNull(3) ? null : reader.GetString(3), reader.IsDBNull(4) ? null : reader.GetString(4)); if (current != expected) return new(action, expected.ProcessId, false, "pid-reused", "The PID now identifies a different backend session."); } await using var command = new NpgsqlCommand(terminate ? "SELECT pg_terminate_backend(@pid)" : "SELECT pg_cancel_backend(@pid)", connection); command.Parameters.AddWithValue("pid", expected.ProcessId); var accepted = Convert.ToBoolean(await command.ExecuteScalarAsync(token)); return new(action, expected.ProcessId, accepted, accepted ? "accepted" : "rejected", accepted ? "PostgreSQL accepted the request; completion must be confirmed by refresh." : "PostgreSQL rejected the request or the session completed."); } catch (PostgresException) { return new(action, expected.ProcessId, false, "permission-or-database-error", "PostgreSQL denied the action or the backend changed state."); } }
}
