using Npgsql;
using PostgreManagementStudio.Application;

namespace PostgreManagementStudio.Postgres;

public sealed class NpgsqlActivityService(INpgsqlConnectionFactory? connectionFactory = null)
{
    private readonly INpgsqlConnectionFactory _connections = connectionFactory ?? NpgsqlConnectionFactory.Shared;
    private const string ActivitySql = "SELECT pid,datname,usename,application_name,client_addr::text,client_port,backend_type,state,query_start,xact_start,state_change,clock_timestamp()-COALESCE(query_start,backend_start),clock_timestamp()-xact_start,wait_event_type,wait_event,query,backend_start FROM pg_stat_activity WHERE pid <> pg_backend_pid() ORDER BY pid";
    private const string BlockingSql = "SELECT blocked.pid, blocker.pid, blocked.datname, blocked.usename, blocked.query, blocker.query, blocked.wait_event FROM pg_stat_activity blocked JOIN LATERAL unnest(pg_blocking_pids(blocked.pid)) AS b(pid) ON true JOIN pg_stat_activity blocker ON blocker.pid=b.pid";
    private const string LocksSql = "SELECT l.pid,l.locktype,d.datname,l.relation::text,l.page,l.tuple,l.virtualxid,l.transactionid,l.mode,l.granted,l.fastpath FROM pg_locks l LEFT JOIN pg_database d ON d.oid=l.database WHERE l.pid IS NOT NULL ORDER BY l.pid";
    public async Task<ActivitySnapshot> LoadSnapshotAsync(string connectionString, long sequence, CancellationToken cancellationToken = default)
    {
        await using var connection = _connections.Create(connectionString, "PostgreManagementStudio - Activity Monitor"); await connection.OpenAsync(cancellationToken); var sessions = new List<BackendSession>();
        await using (var command = new NpgsqlCommand(ActivitySql, connection)) await using (var reader = await command.ExecuteReaderAsync(cancellationToken)) while (await reader.ReadAsync(cancellationToken)) sessions.Add(new(reader.GetInt32(0), Text(reader, 1), Text(reader, 2), Text(reader, 3), Text(reader, 4), Int(reader, 5), Text(reader, 6), Text(reader, 7), Date(reader, 8), Date(reader, 9), Date(reader, 10), Span(reader, 11) ?? TimeSpan.Zero, Span(reader, 12), Text(reader, 13), Text(reader, 14), false, 0, Text(reader, 15), false, Date(reader, 16)));
        var blocking = new List<BlockingRelationship>(); await using (var command = new NpgsqlCommand(BlockingSql, connection)) await using (var reader = await command.ExecuteReaderAsync(cancellationToken)) while (await reader.ReadAsync(cancellationToken)) blocking.Add(new(reader.GetInt32(0), reader.GetInt32(1), 1, Text(reader, 2), Text(reader, 3), Text(reader, 4), Text(reader, 5), Text(reader, 6)));
        var locks = new List<BackendLock>(); await using (var command = new NpgsqlCommand(LocksSql, connection)) await using (var reader = await command.ExecuteReaderAsync(cancellationToken)) while (await reader.ReadAsync(cancellationToken)) locks.Add(new(Int(reader, 0) ?? 0, Text(reader, 1), Text(reader, 2), Text(reader, 3), Int(reader, 4), Int(reader, 5), Text(reader, 6), Long(reader, 7), Text(reader, 8), Convert.ToBoolean(reader.GetValue(9)), Convert.ToBoolean(reader.GetValue(10)), null));
        var blocked = blocking.Select(x => x.BlockedProcessId).ToHashSet(); var blockerCounts = blocking.GroupBy(x => x.BlockingProcessId).ToDictionary(x => x.Key, x => x.Count()); sessions = sessions.Select(s => s with { Blocked = blocked.Contains(s.ProcessId), BlockingCount = blockerCounts.GetValueOrDefault(s.ProcessId) }).ToList(); var now = DateTimeOffset.UtcNow; var summary = new ActivitySummary(sessions.Count, sessions.Count(x => x.ClassifiedState == BackendState.Active), sessions.Count(x => x.ClassifiedState == BackendState.Idle), sessions.Count(x => x.ClassifiedState is BackendState.IdleInTransaction or BackendState.IdleInTransactionAborted), sessions.Count(x => x.ClassifiedState == BackendState.Waiting), sessions.Count(x => x.Blocked), sessions.Count(x => x.BlockingCount > 0), sessions.Count(x => x.Duration >= TimeSpan.FromSeconds(30)), sessions.GroupBy(x => x.Database ?? "").ToDictionary(x => x.Key, x => x.Count()), null, now); return new(sequence, now, sessions, blocking, locks, summary);
    }
    public async Task<BackendActionResult> CancelAsync(string connectionString, int processId, CancellationToken cancellationToken = default) => await ActionAsync(connectionString, "SELECT pg_cancel_backend(@process_id);", processId, "cancel", cancellationToken);
    public async Task<BackendActionResult> TerminateAsync(string connectionString, BackendSession target, int currentPid, int? monitorPid, int? editorPid, CancellationToken cancellationToken = default) { var safety = BackendSafety.ValidateTermination(target, currentPid, monitorPid, editorPid); return !safety.Accepted ? safety : await ActionAsync(connectionString, "SELECT pg_terminate_backend(@process_id);", target.ProcessId, "terminate", cancellationToken); }
    private async Task<BackendActionResult> ActionAsync(string cs, string sql, int pid, string action, CancellationToken token) { try { await using var connection = _connections.Create(cs, "PostgreManagementStudio - Session Action"); await connection.OpenAsync(token); await using var command = new NpgsqlCommand(sql, connection); command.Parameters.AddWithValue("process_id", pid); var accepted = Convert.ToBoolean(await command.ExecuteScalarAsync(token)); return new(accepted, accepted ? "accepted" : "rejected", accepted ? $"Backend {pid} {action} request accepted." : $"Backend {pid} {action} request was rejected or no longer exists."); } catch (PostgresException) { return new(false, "permission-or-database-error", $"Backend {pid} {action} failed due to PostgreSQL permissions or session state."); } }
    private static string? Text(NpgsqlDataReader r, int i) => r.IsDBNull(i) ? null : r.GetValue(i).ToString(); private static int? Int(NpgsqlDataReader r, int i) => r.IsDBNull(i) ? null : Convert.ToInt32(r.GetValue(i)); private static long? Long(NpgsqlDataReader r, int i) => r.IsDBNull(i) ? null : Convert.ToInt64(r.GetValue(i)); private static DateTimeOffset? Date(NpgsqlDataReader r, int i) => r.IsDBNull(i) ? null : r.GetFieldValue<DateTimeOffset>(i); private static TimeSpan? Span(NpgsqlDataReader r, int i) => r.IsDBNull(i) ? null : r.GetTimeSpan(i);
}
