using System.Text;

namespace PostgreManagementStudio.Application;

public enum MaintenanceOperation { Vacuum, Analyze, Reindex, Cluster }
public enum MaintenanceTargetKind { Database, Schema, Table, Index, System }
public sealed record MaintenanceTarget(MaintenanceTargetKind Kind, string Name, string? Schema = null, IReadOnlyList<string>? Columns = null)
{ public string QualifiedName => Schema is null ? PostgreSqlIdentifierQuoter.Quote(Name) : PostgreSqlIdentifierQuoter.Qualified(Schema, Name); }
public sealed record MaintenanceCapabilities(int MajorVersion)
{
    public bool SupportsVacuumSkipLocked => MajorVersion >= 12; public bool SupportsVacuumIndexCleanup => MajorVersion >= 12; public bool SupportsVacuumTruncate => MajorVersion >= 12; public bool SupportsVacuumParallel => MajorVersion >= 13; public bool SupportsAnalyzeSkipLocked => MajorVersion >= 12; public bool SupportsReindexConcurrently => MajorVersion >= 12; public bool SupportsReindexVerbose => MajorVersion >= 12; public bool SupportsReindexTablespace => MajorVersion >= 9; public bool SupportsClusterVerbose => MajorVersion >= 12;
}
public sealed record MaintenanceOptions(bool Analyze = false, bool Full = false, bool Freeze = false, bool Verbose = false, bool SkipLocked = false, bool DisablePageSkipping = false, bool ProcessToast = false, bool Truncate = true, bool IndexCleanup = true, int? ParallelWorkers = null, string? BufferUsageLimit = null, bool Concurrent = false, string? Tablespace = null, bool ClusterAll = false, TimeSpan? StatementTimeout = null, TimeSpan? LockTimeout = null);
public sealed record MaintenancePlan(MaintenanceOperation Operation, IReadOnlyList<MaintenanceTarget> Targets, MaintenanceOptions Options, MaintenanceCapabilities Capabilities)
{
    public bool IsHighImpact => Options.Full || Operation == MaintenanceOperation.Cluster || (Operation == MaintenanceOperation.Reindex && Targets.Any(x => x.Kind == MaintenanceTargetKind.System));
    public IReadOnlyList<string> Statements => MaintenanceSqlBuilder.Build(this);
}
public sealed record MaintenanceTargetResult(MaintenanceTarget Target, bool Succeeded, string? Error, TimeSpan Elapsed);
public sealed record MaintenanceExecutionResult(string Status, IReadOnlyList<MaintenanceTargetResult> Targets, IReadOnlyList<string> Messages, TimeSpan Elapsed, bool Cancelled)
{ public bool Succeeded => !Cancelled && Targets.Count > 0 && Targets.All(x => x.Succeeded); }
public sealed record MaintenanceHistoryEntry(DateTimeOffset Timestamp, string Server, string Database, string ActingUser, MaintenanceOperation Operation, int TargetCount, string Options, string SanitizedSql, DateTimeOffset Started, DateTimeOffset Ended, string Result, int CompletedTargetCount, int FailedTargetCount, bool VerificationSucceeded);
public static class MaintenanceSqlBuilder
{
    public static IReadOnlyList<string> Build(MaintenancePlan plan)
    { if (plan.Targets.Count == 0) throw new ArgumentException("At least one maintenance target is required."); Validate(plan); return plan.Targets.Select(target => plan.Operation switch { MaintenanceOperation.Vacuum => Vacuum(target, plan.Options, plan.Capabilities), MaintenanceOperation.Analyze => Analyze(target, plan.Options, plan.Capabilities), MaintenanceOperation.Reindex => Reindex(target, plan.Options, plan.Capabilities), MaintenanceOperation.Cluster => Cluster(target, plan.Options, plan.Capabilities), _ => throw new ArgumentOutOfRangeException() }).ToArray(); }
    private static string Vacuum(MaintenanceTarget t, MaintenanceOptions o, MaintenanceCapabilities c) { var b = new StringBuilder("VACUUM"); if (o.Full) b.Append(" FULL"); if (o.Freeze) b.Append(" FREEZE"); if (o.Verbose) b.Append(" VERBOSE"); if (o.Analyze) b.Append(" ANALYZE"); if (o.DisablePageSkipping) b.Append(" DISABLE_PAGE_SKIPPING"); if (!o.Truncate) b.Append(" TRUNCATE FALSE"); if (!o.IndexCleanup) b.Append(" INDEX_CLEANUP FALSE"); if (o.SkipLocked && c.SupportsVacuumSkipLocked) b.Append(" SKIP_LOCKED"); if (o.ParallelWorkers is { } p && c.SupportsVacuumParallel) b.Append(" PARALLEL ").Append(p); if (o.BufferUsageLimit is not null) b.Append(" BUFFER_USAGE_LIMIT '").Append(o.BufferUsageLimit).Append("'"); return b.Append(' ').Append(TargetFor(t)).Append(';').ToString(); }
    private static string Analyze(MaintenanceTarget t, MaintenanceOptions o, MaintenanceCapabilities c) { var b = new StringBuilder("ANALYZE"); if (o.Verbose) b.Append(" VERBOSE"); if (o.SkipLocked && c.SupportsAnalyzeSkipLocked) b.Append(" SKIP_LOCKED"); b.Append(' ').Append(TargetFor(t)); if (t.Columns is { Count: > 0 }) b.Append(" (").Append(string.Join(", ", t.Columns.Select(PostgreSqlIdentifierQuoter.Quote))).Append(')'); return b.Append(';').ToString(); }
    private static string Reindex(MaintenanceTarget t, MaintenanceOptions o, MaintenanceCapabilities c) { var b = new StringBuilder("REINDEX"); if (o.Verbose && c.SupportsReindexVerbose) b.Append(" (VERBOSE)"); if (o.Concurrent) { if (!c.SupportsReindexConcurrently || t.Kind is MaintenanceTargetKind.Database or MaintenanceTargetKind.System) throw new ArgumentException("Concurrent reindex is unsupported for this target or server version."); b.Append(" CONCURRENTLY"); } b.Append(' ').Append(t.Kind switch { MaintenanceTargetKind.System => "SYSTEM " + PostgreSqlIdentifierQuoter.Quote(t.Name), _ => t.Kind.ToString().ToUpperInvariant() + " " + t.QualifiedName }); if (o.Tablespace is not null && c.SupportsReindexTablespace) b.Append(" TABLESPACE ").Append(PostgreSqlIdentifierQuoter.Quote(o.Tablespace)); return b.Append(';').ToString(); }
    private static string Cluster(MaintenanceTarget t, MaintenanceOptions o, MaintenanceCapabilities c) { if (t.Kind != MaintenanceTargetKind.Table && !o.ClusterAll) throw new ArgumentException("Cluster requires a table target unless cluster-all is selected."); var b = new StringBuilder("CLUSTER"); if (o.Verbose && c.SupportsClusterVerbose) b.Append(" VERBOSE"); if (o.ClusterAll) return b.Append(';').ToString(); b.Append(' ').Append(t.QualifiedName); return b.Append(';').ToString(); }
    private static string TargetFor(MaintenanceTarget t) => t.Kind == MaintenanceTargetKind.Database ? "" : t.Kind == MaintenanceTargetKind.Schema ? "" : t.QualifiedName;
    private static void Validate(MaintenancePlan p) { var o = p.Options; if (o.Full && o.Freeze) throw new ArgumentException("VACUUM FULL and FREEZE cannot be combined."); if (o.ParallelWorkers is < 0) throw new ArgumentOutOfRangeException(nameof(o.ParallelWorkers)); if (o.Analyze is false && p.Targets.Any(x => x.Columns is { Count: > 0 })) throw new ArgumentException("Column selection requires ANALYZE."); if (p.Operation == MaintenanceOperation.Reindex && p.Targets.Any(x => x.Kind == MaintenanceTargetKind.System) && p.Targets.Count != 1) throw new ArgumentException("REINDEX SYSTEM must be selected alone."); if (p.Operation == MaintenanceOperation.Vacuum && o.Full && o.ParallelWorkers is not null) throw new ArgumentException("VACUUM FULL does not support parallel workers."); }
}
public sealed class MaintenanceHistoryService(int maximumEntries = 100)
{ private readonly LinkedList<MaintenanceHistoryEntry> _entries = new(); public IReadOnlyList<MaintenanceHistoryEntry> Entries => _entries.ToArray(); public void Add(MaintenanceHistoryEntry entry) { _entries.AddFirst(entry); while (_entries.Count > Math.Max(1, maximumEntries)) _entries.RemoveLast(); } public void Clear() => _entries.Clear(); }
