using System.Text.Json;
using System.Security.Cryptography;
using System.Text;

namespace PostgreManagementStudio.Application;

public enum RowEstimateClassification { Accurate, ModerateMismatch, LargeMismatch, SevereMismatch, Unavailable }
public enum PlanChangeKind { Unchanged, Modified, Added, Removed, Replaced, Unmatched }
public sealed record PlanNodeAnalysis(string NodeId, ExecutionPlanNode Node, int Depth, TimeSpan? InclusiveRuntime, TimeSpan? EstimatedExclusiveRuntime, double? RuntimeContributionPercent, double? RowEstimateFactor, RowEstimateClassification RowClassification);
public sealed record PlanComparisonResult(bool PossiblyDifferentQueries, IReadOnlyList<(PlanChangeKind Kind, string Path, string Description)> Changes, string Warning);
public static class ExecutionPlanAnalysisService
{
    public static IReadOnlyList<PlanNodeAnalysis> Analyse(ExecutionPlanDocument document, double accurate = 2, double large = 10, double severe = 100)
    { var all = Flatten(document.Root, "0", 0).ToArray(); var total = document.ExecutionTime; return all.Select(x => { var n = x.Node; TimeSpan? inclusive = n.ActualTime is null || n.Loops is null ? null : TimeSpan.FromMilliseconds(n.ActualTime.Value * Math.Max(1, n.Loops.Value)); var children = n.Children.Sum(c => c.ActualTime is null || c.Loops is null ? 0 : c.ActualTime.Value * Math.Max(1, c.Loops.Value)); TimeSpan? exclusive = inclusive is null ? null : TimeSpan.FromMilliseconds(Math.Max(0, inclusive.Value.TotalMilliseconds - children)); double? factor = n.ActualRows is null || n.PlanRows is null || n.PlanRows <= 0 ? null : Math.Max(n.ActualRows.Value, 1) / Math.Max(n.PlanRows.Value, 1); var classification = factor is null ? RowEstimateClassification.Unavailable : factor <= accurate && factor >= 1 / accurate ? RowEstimateClassification.Accurate : factor <= large && factor >= 1 / large ? RowEstimateClassification.ModerateMismatch : factor <= severe && factor >= 1 / severe ? RowEstimateClassification.LargeMismatch : RowEstimateClassification.SevereMismatch; var contribution = total is null || inclusive is null || total <= 0 ? (double?)null : inclusive.Value.TotalMilliseconds / total.Value * 100; return new PlanNodeAnalysis(x.Id, n, x.Depth, inclusive, exclusive, contribution, factor, classification); }).ToArray(); }
    public static string NodeId(ExecutionPlanNode node, string path) { var seed = $"{path}|{node.NodeType}|{node.Schema}|{node.RelationName}|{node.IndexName}"; return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(seed)))[..16]; }
    private static IEnumerable<(ExecutionPlanNode Node, string Id, int Depth)> Flatten(ExecutionPlanNode node, string path, int depth) { yield return (node, NodeId(node, path), depth); for (var i = 0; i < node.Children.Count; i++) foreach (var child in Flatten(node.Children[i], path + "." + i, depth + 1)) yield return child; }
}
public static class PlanDiagnosticEngine
{
    public static IReadOnlyList<PlanDiagnostic> Diagnose(ExecutionPlanDocument document)
    { var diagnostics = new List<PlanDiagnostic>(); foreach (var node in ExecutionPlanAnalysisService.Analyse(document)) { if (node.RowClassification is RowEstimateClassification.LargeMismatch or RowEstimateClassification.SevereMismatch) diagnostics.Add(new("Warning", node.Node.NodeType, $"Estimated rows {node.Node.PlanRows:N0}; actual rows {node.Node.ActualRows:N0}; factor {node.RowEstimateFactor:N1}x.", "The estimate differs materially from runtime rows; this can affect planner choices.", "Investigate statistics, data skew, correlated predicates, and parameter sensitivity. This is diagnostic guidance, not a guaranteed fix.")); if (node.Node.NodeType.Contains("Sort", StringComparison.OrdinalIgnoreCase) && node.Node.UnknownFields.TryGetValue("Sort Method", out var method) && method.GetString()?.Contains("external", StringComparison.OrdinalIgnoreCase) == true) diagnostics.Add(new("Warning", node.Node.NodeType, "External sort method indicates temporary disk use.", "The sort spilled outside memory during execution.", "Investigate work_mem, result size, and available ordering; raising work_mem globally has per-operation memory costs.")); if (node.Node.NodeType.Contains("Hash", StringComparison.OrdinalIgnoreCase) && node.Node.UnknownFields.TryGetValue("Hash Batches", out var batches) && batches.TryGetInt32(out var count) && count > 1) diagnostics.Add(new("Notice", node.Node.NodeType, $"Hash operation used {count} batches.", "Multiple batches can indicate temporary I/O or memory pressure.", "Inspect memory and workload context before changing settings.")); } return diagnostics; }
}
public static class ExecutionPlanComparisonService
{
    public static PlanComparisonResult Compare(ExecutionPlanDocument before, ExecutionPlanDocument after)
    { var warning = before.QueryText == after.QueryText ? "" : "These plans may represent different SQL statements or parameters; interpret differences with caution."; var changes = new List<(PlanChangeKind, string, string)>(); CompareNode(before.Root, after.Root, "0", changes); return new(!string.IsNullOrEmpty(warning), changes, warning); }
    private static void CompareNode(ExecutionPlanNode? before, ExecutionPlanNode? after, string path, List<(PlanChangeKind, string, string)> changes) { if (before is null) { changes.Add((PlanChangeKind.Added, path, $"Added {after!.NodeType}")); return; } if (after is null) { changes.Add((PlanChangeKind.Removed, path, $"Removed {before.NodeType}")); return; } if (before.NodeType != after.NodeType || before.RelationName != after.RelationName || before.IndexName != after.IndexName) changes.Add((before.RelationName == after.RelationName && before.Schema == after.Schema ? PlanChangeKind.Replaced : PlanChangeKind.Modified, path, $"{before.NodeType} changed to {after.NodeType}")); else if (before.TotalCost != after.TotalCost || before.ActualTime != after.ActualTime || before.ActualRows != after.ActualRows) changes.Add((PlanChangeKind.Modified, path, "Node metrics changed")); var count = Math.Max(before.Children.Count, after.Children.Count); for (var i = 0; i < count; i++) CompareNode(i < before.Children.Count ? before.Children[i] : null, i < after.Children.Count ? after.Children[i] : null, path + "." + i, changes); }
}
public static class ExecutionPlanFileService
{
    public static string Save(ExecutionPlanDocument plan, bool includeQueryText = false) => JsonSerializer.Serialize(new { FormatVersion = 1, plan.CapturedAt, plan.Type, QueryText = includeQueryText ? plan.QueryText : null, plan.RawJson }, new JsonSerializerOptions { WriteIndented = true });
    public static ExecutionPlanDocument Open(string content, CancellationToken cancellationToken = default) { cancellationToken.ThrowIfCancellationRequested(); using var doc = JsonDocument.Parse(content); var raw = doc.RootElement.TryGetProperty("RawJson", out var value) ? value.GetString() : content; if (string.IsNullOrWhiteSpace(raw)) throw new InvalidDataException("The plan file does not contain a JSON plan."); var query = doc.RootElement.TryGetProperty("QueryText", out var q) && q.ValueKind == JsonValueKind.String ? q.GetString() ?? "" : ""; var type = doc.RootElement.TryGetProperty("Type", out var t) ? t.ValueKind == JsonValueKind.Number ? (PlanType)t.GetInt32() : Enum.TryParse<PlanType>(t.GetString(), true, out var parsed) ? parsed : PlanType.Estimated : PlanType.Estimated; return ExecutionPlanParser.Parse(query, raw, type); }
}
