using System.Text.Json;

namespace PostgreManagementStudio.Application;

public enum PlanWarningSeverity { Information, Review, Significant, Critical }
public sealed record PlanExplorerNodeRow(string NodeId, int Number, int Depth, string? ParentId, ExecutionPlanNode Node, TimeSpan? InclusiveTime, TimeSpan? ExclusiveTime, double? CostPercent, double? TimePercent);
public sealed record PlanExplorerWarning(PlanWarningSeverity Severity, string NodeId, string Summary, string Evidence, string Guidance);
public sealed record PlanExplorerSearch(string Text, IReadOnlyList<PlanExplorerNodeRow> Matches);
public sealed record PlanImportResult(bool IsValid, string Format, ExecutionPlanDocument? Plan, string? Error, int? ErrorLine);
public sealed record ExplainCapabilities(bool SupportsWal, bool SupportsMemory, bool SupportsSerialize, bool SupportsSettings, bool SupportsSummary);

public static class ExecutionPlanExplorerService
{
    public static IReadOnlyList<PlanExplorerNodeRow> Flatten(ExecutionPlanDocument plan)
    { var result = new List<PlanExplorerNodeRow>(); var number = 0; Walk(plan.Root, null, "0", 0, result, ref number); return result; }
    public static PlanExplorerSearch Search(ExecutionPlanDocument plan, string text) { var rows = Flatten(plan); if (string.IsNullOrWhiteSpace(text)) return new(text, rows); return new(text, rows.Where(x => x.Node.NodeType.Contains(text, StringComparison.OrdinalIgnoreCase) || (x.Node.RelationName?.Contains(text, StringComparison.OrdinalIgnoreCase) ?? false) || (x.Node.IndexName?.Contains(text, StringComparison.OrdinalIgnoreCase) ?? false) || x.Node.UnknownFields.Values.Any(v => v.ValueKind == JsonValueKind.String && v.GetString()!.Contains(text, StringComparison.OrdinalIgnoreCase))).ToArray()); }
    public static IReadOnlyList<PlanExplorerWarning> Warnings(ExecutionPlanDocument plan)
    { var output = new List<PlanExplorerWarning>(); foreach (var row in Flatten(plan)) { if (row.Node.NodeType.Contains("Seq Scan", StringComparison.OrdinalIgnoreCase) && row.Node.PlanRows > 10000) output.Add(new(PlanWarningSeverity.Review, row.NodeId, "Large sequential scan observed.", $"Estimated rows: {row.Node.PlanRows:N0}.", "Review selectivity and existing access paths; this may be expected for large scans.")); if (row.Node.NodeType.Equals("Sort", StringComparison.OrdinalIgnoreCase) && row.Node.UnknownFields.TryGetValue("Sort Method", out var method) && method.GetString()?.Contains("external", StringComparison.OrdinalIgnoreCase) == true) output.Add(new(PlanWarningSeverity.Significant, row.NodeId, "Sort used an external method.", $"Sort method: {method.GetString()}.", "Review result size and memory settings before changing configuration.")); if (row.Node.ActualRows is not null && row.Node.PlanRows is > 0 && Math.Max(row.Node.ActualRows.Value, 1) / Math.Max(row.Node.PlanRows.Value, 1) > 100) output.Add(new(PlanWarningSeverity.Significant, row.NodeId, "Severe row-estimation mismatch.", $"Estimated {row.Node.PlanRows:N0}; actual {row.Node.ActualRows:N0}.", "Review statistics, skew, and predicate selectivity.")); } return output.GroupBy(x => (x.NodeId, x.Summary)).Select(x => x.First()).OrderByDescending(x => x.Severity).ThenBy(x => x.NodeId).ToArray(); }
    public static PlanImportResult Import(string content, PlanType type = PlanType.Estimated, CancellationToken cancellationToken = default) { try { cancellationToken.ThrowIfCancellationRequested(); using var doc = JsonDocument.Parse(content); var plan = ExecutionPlanParser.Parse("", content, type); return new(true, "PostgreSQL JSON", plan, null, null); } catch (JsonException ex) { return new(false, "Unknown", null, $"Malformed JSON: {ex.Message}", (int?)ex.LineNumber); } catch (Exception ex) { return new(false, "Unknown", null, ex.Message, null); } }
    public static ExplainCapabilities ForPostgreSqlMajor(int major) => new(major >= 10, major >= 13, major >= 14, major >= 9, major >= 9);
    private static void Walk(ExecutionPlanNode node, string? parent, string path, int depth, List<PlanExplorerNodeRow> output, ref int number) { var id = ExecutionPlanAnalysisService.NodeId(node, path); var inclusive = node.ActualTime is null || node.Loops is null ? (TimeSpan?)null : TimeSpan.FromMilliseconds(node.ActualTime.Value * Math.Max(1, node.Loops.Value)); var childMs = node.Children.Sum(x => x.ActualTime is null || x.Loops is null ? 0 : x.ActualTime.Value * Math.Max(1, x.Loops.Value)); TimeSpan? exclusive = inclusive is null ? null : TimeSpan.FromMilliseconds(Math.Max(0, inclusive.Value.TotalMilliseconds - childMs)); var rootCost = output.Count == 0 ? node.TotalCost : output[0].Node.TotalCost; output.Add(new(id, ++number, depth, parent, node, inclusive, exclusive, rootCost is > 0 && node.TotalCost is not null ? node.TotalCost / rootCost * 100 : null, null)); for (var i = 0; i < node.Children.Count; i++) Walk(node.Children[i], id, path + "." + i, depth + 1, output, ref number); }
}
