using System.Text.Json;
using System.Text.RegularExpressions;

namespace PostgreManagementStudio.Application;

public enum PlanType { Estimated, Actual }
public enum ActualPlanSafety { Rollback, Normal, Cancel }
public sealed record ExplainOptions(PlanType Type = PlanType.Estimated, bool Verbose = true, bool Costs = true, bool Buffers = false, bool Settings = true, bool Summary = true, bool Timing = true, TimeSpan? StatementTimeout = null, ActualPlanSafety Safety = ActualPlanSafety.Rollback);
public sealed record ExplainRequest(string Sql, ExplainOptions Options);
public sealed record ExplainCommand(string Sql, bool IsDataChanging, bool RequiresConfirmation, IReadOnlyList<string> Warnings);
public sealed record ExecutionPlanNode(string NodeType, string? RelationName, string? Schema, string? Alias, string? IndexName, double? StartupCost, double? TotalCost, double? PlanRows, double? ActualRows, double? ActualTime, double? Loops, IReadOnlyList<ExecutionPlanNode> Children, IReadOnlyDictionary<string, JsonElement> UnknownFields);
public sealed record ExecutionPlanDocument(string QueryText, PlanType Type, ExecutionPlanNode Root, string RawJson, double? PlanningTime, double? ExecutionTime, DateTimeOffset CapturedAt);
public sealed record PlanDiagnostic(string Severity, string NodeType, string Evidence, string Explanation, string Investigation);
public sealed record PlanSummary(int NodeCount, int MaxDepth, int SequentialScans, int IndexScans, int Joins, int Sorts, double? TotalCost, double? RootRows, double? ActualRows, double? PlanningTime, double? ExecutionTime);
public sealed record PlanHistoryEntry(string Name, string QueryText, PlanType Type, string Server, string Database, DateTimeOffset CapturedAt, string RawJson, string Notes, IReadOnlyList<string> Tags);
public static class ExplainCommandBuilder
{
    private static readonly Regex Mutating = new(@"^\s*(INSERT|UPDATE|DELETE|MERGE|CALL|DO|CREATE|ALTER|DROP|TRUNCATE|GRANT|REVOKE|VACUUM|ANALYZE|REFRESH)\b", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    public static ExplainCommand Build(ExplainRequest request) { var sql = request.Sql.Trim(); if (string.IsNullOrWhiteSpace(sql)) throw new ArgumentException("SQL to explain is required."); if (ContainsMultipleStatements(sql)) throw new ArgumentException("Select one statement before generating an execution plan."); var changing = Mutating.IsMatch(sql); var warnings = new List<string>(); if (changing) warnings.Add("This statement may change data or cause external side effects."); if (request.Options.Type == PlanType.Actual && changing && request.Options.Safety == ActualPlanSafety.Normal) warnings.Add("Normal execution is explicitly destructive and requires confirmation."); var clauses = new List<string>(); if (request.Options.Type == PlanType.Actual) clauses.Add("ANALYZE TRUE"); clauses.Add("FORMAT JSON"); if (request.Options.Verbose) clauses.Add("VERBOSE TRUE"); if (request.Options.Costs) clauses.Add("COSTS TRUE"); if (request.Options.Buffers && request.Options.Type == PlanType.Actual) clauses.Add("BUFFERS TRUE"); if (request.Options.Settings) clauses.Add("SETTINGS TRUE"); if (request.Options.Summary) clauses.Add("SUMMARY TRUE"); if (request.Options.Timing && request.Options.Type == PlanType.Actual) clauses.Add("TIMING TRUE"); return new($"EXPLAIN ({string.Join(", ", clauses)})\n{sql.TrimEnd(';')};", changing, request.Options.Type == PlanType.Actual && changing, warnings); }
    private static bool ContainsMultipleStatements(string sql) { var quote = false; var lineComment = false; for (var i = 0; i < sql.Length; i++) { if (sql[i] == '\'' && !lineComment) quote = !quote; if (!quote && i + 1 < sql.Length && sql[i] == '-' && sql[i + 1] == '-') lineComment = true; if (lineComment && sql[i] == '\n') lineComment = false; if (!quote && !lineComment && sql[i] == ';' && sql[(i + 1)..].Trim().Length > 0) return true; } return false; }
}
public static class ExecutionPlanParser
{
    public static ExecutionPlanDocument Parse(string query, string json, PlanType type) { using var document = JsonDocument.Parse(json); var root = document.RootElement.ValueKind == JsonValueKind.Array ? document.RootElement[0] : document.RootElement; var plan = root.GetProperty("Plan"); var node = ParseNode(plan); return new(query, type, node, json, Number(root, "Planning Time"), Number(root, "Execution Time"), DateTimeOffset.UtcNow); }
    private static ExecutionPlanNode ParseNode(JsonElement e) { var children = e.TryGetProperty("Plans", out var plans) ? plans.EnumerateArray().Select(ParseNode).ToArray() : Array.Empty<ExecutionPlanNode>(); var known = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Node Type", "Relation Name", "Schema", "Alias", "Index Name", "Startup Cost", "Total Cost", "Plan Rows", "Actual Rows", "Actual Total Time", "Actual Loops", "Plans" }; return new(e.TryGetProperty("Node Type", out var t) ? t.GetString() ?? "Unknown" : "Unknown", Text(e, "Relation Name"), Text(e, "Schema"), Text(e, "Alias"), Text(e, "Index Name"), Number(e, "Startup Cost"), Number(e, "Total Cost"), Number(e, "Plan Rows"), Number(e, "Actual Rows"), Number(e, "Actual Total Time"), Number(e, "Actual Loops"), children, e.EnumerateObject().Where(x => !known.Contains(x.Name)).ToDictionary(x => x.Name, x => x.Value.Clone())); }
    private static string? Text(JsonElement e, string name) => e.TryGetProperty(name, out var value) ? value.GetString() : null; private static double? Number(JsonElement e, string name) => e.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number && value.TryGetDouble(out var number) ? number : null;
}
public static class PlanMetricsService
{ public static PlanSummary Summarize(ExecutionPlanDocument plan) { var nodes = Nodes(plan.Root).ToArray(); return new(nodes.Length, Depth(plan.Root), nodes.Count(x => x.NodeType.Contains("Seq Scan", StringComparison.OrdinalIgnoreCase)), nodes.Count(x => x.NodeType.Contains("Index", StringComparison.OrdinalIgnoreCase)), nodes.Count(x => x.NodeType.Contains("Join", StringComparison.OrdinalIgnoreCase)), nodes.Count(x => x.NodeType.Equals("Sort", StringComparison.OrdinalIgnoreCase)), plan.Root.TotalCost, plan.Root.PlanRows, plan.Root.ActualRows, plan.PlanningTime, plan.ExecutionTime); } public static IReadOnlyList<PlanDiagnostic> Diagnose(ExecutionPlanDocument plan) => Nodes(plan.Root).Where(x => x.NodeType.Contains("Seq Scan", StringComparison.OrdinalIgnoreCase) && x.PlanRows > 10000).Select(x => new PlanDiagnostic("Warning", x.NodeType, $"Estimated rows: {x.PlanRows}", "A sequential scan has a large estimated row set; this is an observation, not proof of a problem.", "Inspect selectivity, statistics, and access paths.")).ToArray(); private static IEnumerable<ExecutionPlanNode> Nodes(ExecutionPlanNode n) => new[] { n }.Concat(n.Children.SelectMany(Nodes)); private static int Depth(ExecutionPlanNode n) => n.Children.Count == 0 ? 1 : 1 + n.Children.Max(Depth); }
public sealed class PlanHistoryService(int maximumEntries = 100) { private readonly LinkedList<PlanHistoryEntry> _entries = new(); public IReadOnlyList<PlanHistoryEntry> Entries => _entries.ToArray(); public void Add(PlanHistoryEntry entry) { _entries.AddFirst(entry); while (_entries.Count > Math.Max(1, maximumEntries)) _entries.RemoveLast(); } public void Clear() => _entries.Clear(); }
