namespace PostgreManagementStudio.Application;

public sealed record IndexAnalysisScope(string? Database = null, string? Schema = null, string? Table = null, string? Index = null);
public sealed record IndexWorkspaceSummary(int TotalIndexes, long TotalIndexBytes, int InvalidIndexes, int DuplicateGroups, int OverlapGroups, int MissingForeignKeyIndexes, int ProtectedIndexes, int ReviewRecommendations);
public sealed record IndexEvidence(string Source, string? QueryText, string? PlanNodeId, string Explanation);
public sealed record MissingIndexCandidate(string Schema, string Table, IReadOnlyList<string> KeyColumns, IReadOnlyList<string> IncludedColumns, string? Predicate, string AccessMethod, RecommendationConfidence Confidence, IReadOnlyList<IndexEvidence> Evidence, string SqlPreview, IReadOnlyList<string> Limitations);
public sealed record IndexCandidateValidation(bool IsValid, IReadOnlyList<string> Errors, IReadOnlyList<string> Warnings);
public static class IndexWorkspaceService
{
    // Index metadata is loaded for one database at a time. Database is therefore
    // workspace context, while the remaining fields are filters over this set.
    public static IReadOnlyList<IndexMetadata> ApplyScope(IEnumerable<IndexMetadata> indexes, IndexAnalysisScope scope) =>
        indexes.Where(x =>
            (string.IsNullOrEmpty(scope.Schema) || x.SchemaName == scope.Schema) &&
            (string.IsNullOrEmpty(scope.Table) || x.TableName == scope.Table) &&
            (string.IsNullOrEmpty(scope.Index) || x.IndexName == scope.Index)).ToArray();
    public static IndexWorkspaceSummary Summarize(IEnumerable<IndexMetadata> indexes, IEnumerable<ForeignKeyMetadata> foreignKeys)
    { var all = indexes.ToArray(); var duplicates = IndexAnalysisService.FindDuplicates(all); var overlaps = IndexAnalysisService.FindOverlaps(all); var recommendations = IndexAnalysisService.Recommend(all, foreignKeys); return new(all.Length, all.Sum(x => x.SizeBytes), all.Count(x => !x.IsValid || !x.IsReady || !x.IsLive), duplicates.Count, overlaps.Count, recommendations.Count(x => x.Category == IndexRecommendationCategory.MissingForeignKey), all.Count(x => x.IsPrimary || x.IsConstraintBacked || x.IsReplicaIdentity), recommendations.Count); }
    public static MissingIndexCandidate FromPlan(ExecutionPlanNode node, string schema, string table, IReadOnlyList<string> keys, IReadOnlyList<IndexEvidence> evidence, string? predicate = null, IReadOnlyList<string>? includes = null)
    { var safeKeys = keys.Where(x => !string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).ToArray(); var sql = $"CREATE INDEX CONCURRENTLY {PostgreSqlIdentifierQuoter.Quote($"ix_{table}_{string.Join("_", safeKeys)}")} ON {PostgreSqlIdentifierQuoter.Qualified(schema, table)} ({string.Join(", ", safeKeys.Select(PostgreSqlIdentifierQuoter.Quote))})" + (includes is { Count: > 0 } ? $" INCLUDE ({string.Join(", ", includes.Select(PostgreSqlIdentifierQuoter.Quote))})" : "") + (predicate is null ? "" : " WHERE " + predicate) + ";"; return new(schema, table, safeKeys, includes ?? Array.Empty<string>(), predicate, "btree", evidence.Count >= 3 ? RecommendationConfidence.High : evidence.Count == 2 ? RecommendationConfidence.Moderate : RecommendationConfidence.Low, evidence, sql, new[] { "The candidate is based on plan evidence and must be validated with representative workload and write-cost measurements.", "CREATE INDEX CONCURRENTLY cannot run inside a transaction." }); }
    public static IndexCandidateValidation Validate(MissingIndexCandidate candidate, IEnumerable<IndexMetadata> existing, int postgresMajor = 16)
    { var errors = new List<string>(); var warnings = new List<string>(); if (candidate.KeyColumns.Count == 0) errors.Add("At least one key column is required."); if (candidate.KeyColumns.Distinct(StringComparer.OrdinalIgnoreCase).Count() != candidate.KeyColumns.Count) errors.Add("Key columns must be unique."); if (candidate.IncludedColumns.Any(x => candidate.KeyColumns.Contains(x, StringComparer.OrdinalIgnoreCase))) errors.Add("Included columns must not duplicate key columns."); if (candidate.AccessMethod != "btree") warnings.Add("Specialized access methods require operator-specific evidence."); if (candidate.Predicate?.Contains("now(", StringComparison.OrdinalIgnoreCase) == true) errors.Add("Volatile predicates are not valid candidate predicates."); if (postgresMajor < 9 && candidate.IncludedColumns.Count > 0) errors.Add("INCLUDE columns are unsupported on this PostgreSQL version."); if (existing.Any(x => x.SchemaName == candidate.Schema && x.TableName == candidate.Table && x.Keys.Select(k => k.Expression).SequenceEqual(candidate.KeyColumns, StringComparer.OrdinalIgnoreCase))) warnings.Add("An existing index has the same leading key columns; review overlap before creation."); return new(errors.Count == 0, errors, warnings); }
}
