using System.Text;
using System.Text.Json;

namespace PostgreManagementStudio.Application;

public enum PlanMatchConfidence { High, Medium, Low }
public enum PlanNodeChangeType { Unchanged, Modified, Added, Removed, Moved, Unmatched }
public enum PlanRegressionClassification { Improved, LikelyImproved, Mixed, NoMaterialChange, LikelyRegressed, Regressed, InsufficientData }
public sealed record PlanComparisonOptions(bool AllowDifferentQueries = true, double MaterialChangePercent = 20);
public sealed record PlanNodeMatch(string BaselinePath, string CandidatePath, PlanNodeChangeType Change, PlanMatchConfidence Confidence, string Reason, ExecutionPlanNode? Baseline, ExecutionPlanNode? Candidate)
{ public static implicit operator PlanNodeMatch((string BaselinePath, string CandidatePath, PlanNodeChangeType Change, PlanMatchConfidence Confidence, string Reason, ExecutionPlanNode? Baseline, ExecutionPlanNode? Candidate) value) => new(value.BaselinePath, value.CandidatePath, value.Change, value.Confidence, value.Reason, value.Baseline, value.Candidate); }
public sealed record PlanNumericDifference(double? Baseline, double? Candidate, double? Absolute, double? Percent, string Status);
public sealed record PlanRegressionThresholds(double WarningPercent = 20, double SignificantPercent = 50, double MinimumAbsoluteMilliseconds = 1);
public sealed record PlanRegressionAssessment(PlanRegressionClassification Classification, IReadOnlyList<string> Evidence, IReadOnlyList<string> Improvements, IReadOnlyList<string> Warnings);
public sealed record ExecutionPlanComparison(ExecutionPlanDocument Baseline, ExecutionPlanDocument Candidate, IReadOnlyList<PlanNodeMatch> Matches, IReadOnlyList<string> CompatibilityWarnings, PlanRegressionAssessment Assessment, DateTimeOffset ComparedAt);

public static class PlanComparisonService
{
    public static string QueryFingerprint(string sql) => string.Join(' ', sql.Trim().TrimEnd(';').Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
    public static PlanNumericDifference Difference(double? baseline, double? candidate)
    { if (baseline is null || candidate is null) return new(baseline, candidate, null, null, "Unavailable"); var absolute = candidate - baseline; if (baseline == 0) return new(baseline, candidate, absolute, null, "Baseline was zero; percentage change is not applicable."); return new(baseline, candidate, absolute, absolute / Math.Abs(baseline.Value) * 100, "Available"); }
    public static ExecutionPlanComparison Compare(ExecutionPlanDocument baseline, ExecutionPlanDocument candidate, PlanComparisonOptions? options = null, PlanRegressionThresholds? thresholds = null, CancellationToken cancellationToken = default)
    { options ??= new(); thresholds ??= new(); var warnings = new List<string>(); if (QueryFingerprint(baseline.QueryText) != QueryFingerprint(candidate.QueryText)) warnings.Add("Query text differs; interpret comparison with caution."); if (baseline.Type != candidate.Type) warnings.Add("One plan is estimated and the other is actual."); var matches = new List<PlanNodeMatch>(); Match(baseline.Root, candidate.Root, "0", "0", matches, cancellationToken); var assessment = Assess(baseline, candidate, thresholds, matches); return new(baseline, candidate, matches.OrderBy(x => x.BaselinePath, StringComparer.Ordinal).ThenBy(x => x.CandidatePath, StringComparer.Ordinal).ToArray(), warnings, assessment, DateTimeOffset.UtcNow); }
    public static string Save(ExecutionPlanComparison comparison) => JsonSerializer.Serialize(new { SchemaVersion = 1, comparison.ComparedAt, Baseline = ExecutionPlanFileService.Save(comparison.Baseline, true), Candidate = ExecutionPlanFileService.Save(comparison.Candidate, true), comparison.CompatibilityWarnings, comparison.Assessment }, new JsonSerializerOptions { WriteIndented = true });
    public static ExecutionPlanComparison Open(string content, CancellationToken token = default) { token.ThrowIfCancellationRequested(); using var doc = JsonDocument.Parse(content); if (!doc.RootElement.TryGetProperty("SchemaVersion", out var version) || version.GetInt32() != 1) throw new InvalidDataException("Unsupported plan comparison schema version."); var baseline = ExecutionPlanFileService.Open(doc.RootElement.GetProperty("Baseline").GetString()!, token); var candidate = ExecutionPlanFileService.Open(doc.RootElement.GetProperty("Candidate").GetString()!, token); return Compare(baseline, candidate, cancellationToken: token); }
    public static string Markdown(ExecutionPlanComparison comparison)
    { var b = new StringBuilder("# Execution Plan Comparison\n\n"); b.AppendLine($"- Compared: {comparison.ComparedAt:O}"); b.AppendLine($"- Baseline: {comparison.Baseline.Type}"); b.AppendLine($"- Candidate: {comparison.Candidate.Type}"); b.AppendLine($"- Classification: **{comparison.Assessment.Classification}**\n"); if (comparison.CompatibilityWarnings.Count > 0) { b.AppendLine("## Compatibility warnings"); foreach (var x in comparison.CompatibilityWarnings) b.AppendLine($"- {x}"); b.AppendLine(); } b.AppendLine("## Assessment"); foreach (var x in comparison.Assessment.Evidence) b.AppendLine($"- Regression evidence: {x}"); foreach (var x in comparison.Assessment.Improvements) b.AppendLine($"- Improvement: {x}"); b.AppendLine("\n## Structural changes"); foreach (var m in comparison.Matches.Where(x => x.Change != PlanNodeChangeType.Unchanged)) b.AppendLine($"- {m.Change}: {m.Baseline?.NodeType ?? "(none)"} -> {m.Candidate?.NodeType ?? "(none)"} ({m.Confidence} confidence)"); return b.ToString(); }
    private static void Match(ExecutionPlanNode before, ExecutionPlanNode after, string bp, string cp, List<PlanNodeMatch> output, CancellationToken token)
    { token.ThrowIfCancellationRequested(); var sameIdentity = before.NodeType == after.NodeType && before.RelationName == after.RelationName && before.Schema == after.Schema && before.IndexName == after.IndexName; var change = !sameIdentity ? PlanNodeChangeType.Modified : before.TotalCost != after.TotalCost || before.PlanRows != after.PlanRows || before.ActualTime != after.ActualTime || before.ActualRows != after.ActualRows ? PlanNodeChangeType.Modified : PlanNodeChangeType.Unchanged; output.Add(new(bp, cp, change, sameIdentity ? PlanMatchConfidence.High : PlanMatchConfidence.Low, sameIdentity ? "Same node type, relation, schema, and index." : "Node identity differs; positional match is low confidence.", before, after)); var used = new HashSet<int>(); for (var i = 0; i < before.Children.Count; i++) { var match = Enumerable.Range(0, after.Children.Count).Where(x => !used.Contains(x)).OrderBy(x => Score(before.Children[i], after.Children[x])).ThenBy(x => x).FirstOrDefault(-1); if (match < 0 || Score(before.Children[i], after.Children[match]) == 0) output.Add(new($"{bp}.{i}", "", PlanNodeChangeType.Removed, PlanMatchConfidence.Low, "No compatible candidate node found.", before.Children[i], null)); else { used.Add(match); Match(before.Children[i], after.Children[match], $"{bp}.{i}", $"{cp}.{match}", output, token); } } for (var i = 0; i < after.Children.Count; i++) if (!used.Contains(i)) output.Add(("", $"{cp}.{i}", PlanNodeChangeType.Added, PlanMatchConfidence.Low, "Candidate node has no baseline counterpart.", null, after.Children[i])); }
    private static int Score(ExecutionPlanNode a, ExecutionPlanNode b) => (a.NodeType == b.NodeType ? 4 : 0) + (a.RelationName == b.RelationName ? 3 : 0) + (a.Schema == b.Schema ? 1 : 0) + (a.IndexName == b.IndexName ? 2 : 0);
    private static PlanRegressionAssessment Assess(ExecutionPlanDocument b, ExecutionPlanDocument c, PlanRegressionThresholds t, IReadOnlyList<PlanNodeMatch> matches) { var evidence = new List<string>(); var improvements = new List<string>(); var warnings = new List<string>(); var score = 0; var time = Difference(b.ExecutionTime, c.ExecutionTime); if (time.Percent is > 0 && time.Absolute >= t.MinimumAbsoluteMilliseconds && time.Percent >= t.WarningPercent) { score += time.Percent >= t.SignificantPercent ? 2 : 1; evidence.Add($"Execution time increased by {time.Percent:N1}%."); } else if (time.Percent is < 0 && Math.Abs(time.Percent.Value) >= t.WarningPercent) { score--; improvements.Add($"Execution time decreased by {Math.Abs(time.Percent.Value):N1}%."); } var cost = Difference(b.Root.TotalCost, c.Root.TotalCost); if (cost.Percent is > 0 && cost.Percent >= t.WarningPercent) { score += cost.Percent >= t.SignificantPercent ? 2 : 1; evidence.Add($"Estimated total cost increased by {cost.Percent:N1}%."); } if (matches.Any(x => x.Change == PlanNodeChangeType.Added && x.Candidate?.NodeType.Contains("Seq Scan", StringComparison.OrdinalIgnoreCase) == true)) { score++; evidence.Add("A sequential scan was introduced."); } if (matches.Any(x => x.Change == PlanNodeChangeType.Removed && x.Baseline?.NodeType.Contains("Index Scan", StringComparison.OrdinalIgnoreCase) == true)) { score++; evidence.Add("An index scan was removed."); } var classification = score >= 2 ? PlanRegressionClassification.Regressed : score == 1 ? PlanRegressionClassification.LikelyRegressed : score < 0 ? PlanRegressionClassification.Improved : PlanRegressionClassification.NoMaterialChange; return new(classification, evidence, improvements, warnings); }
}
