<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PostgreManagementStudio.Core\PostgreManagementStudio.Core.csproj" />
    <ProjectReference Include="..\PostgreManagementStudio.Results\PostgreManagementStudio.Results.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>