namespace PostgreManagementStudio.Application;

public enum QueryDashboardQuickFilter { All, HighTotalTime, SlowPerExecution, FrequentlyExecuted, HighVariability, IoHeavy, TemporaryUsers, WalHeavy, LowCacheHit }
public sealed record QueryDashboardThresholds(TimeSpan SlowMean = default, TimeSpan HighTotal = default, long HighCalls = 10000, double HighVariability = 1.0, double LowCacheHitPercent = 80, long HighTemporaryWrites = 1000, decimal HighWalBytes = 1000000) { public TimeSpan EffectiveSlowMean => SlowMean == default ? TimeSpan.FromSeconds(1) : SlowMean; public TimeSpan EffectiveHighTotal => HighTotal == default ? TimeSpan.FromMinutes(10) : HighTotal; }
public sealed record QueryDashboardSummary(int TrackedStatements, long TotalCalls, TimeSpan TotalExecutionTime, TimeSpan MeanExecutionTime, TimeSpan MaximumExecutionTime, long TotalRows, long SharedBlocksRead, long TemporaryBlocksWritten, double? CacheHitPercent, DateTimeOffset? StatisticsResetAt);
public sealed record QueryDashboardDelta(QueryIdentity Identity, long Calls, TimeSpan ExecutionTime, long Rows, long SharedBlocksHit, long SharedBlocksRead, long TemporaryBlocksWritten, decimal? WalBytes, bool IsComparable, string? Reason);
public sealed record QueryStatisticsResetValidation(bool Allowed, string Code, string Message);
public sealed record QueryDashboardAvailability(PgStatStatementsAvailability Availability, string Guidance, bool CanReset, bool RequiresRestart);

public static class QueryDashboardService
{
    public static QueryDashboardSummary Summarize(IEnumerable<QueryStatistics> source, DateTimeOffset? resetAt = null)
    { var q = source.ToArray(); var calls = q.Sum(x => x.Calls); return new(q.Length, calls, TimeSpan.FromTicks(q.Sum(x => x.TotalExecutionTime.Ticks)), calls == 0 ? TimeSpan.Zero : TimeSpan.FromTicks(q.Sum(x => x.TotalExecutionTime.Ticks) / calls), q.Select(x => x.MaximumExecutionTime).DefaultIfEmpty().Max(), q.Sum(x => x.Rows), q.Sum(x => x.SharedBlocksRead), q.Sum(x => x.TemporaryBlocksWritten), CacheHit(q), resetAt); }
    public static IReadOnlyList<QueryStatistics> Filter(IEnumerable<QueryStatistics> source, QueryDashboardQuickFilter filter, QueryDashboardThresholds? thresholds = null) { thresholds ??= new(); return filter switch { QueryDashboardQuickFilter.HighTotalTime => source.Where(x => x.TotalExecutionTime >= thresholds.EffectiveHighTotal).ToArray(), QueryDashboardQuickFilter.SlowPerExecution => source.Where(x => x.MeanExecutionTime >= thresholds.EffectiveSlowMean).ToArray(), QueryDashboardQuickFilter.FrequentlyExecuted => source.Where(x => x.Calls >= thresholds.HighCalls).ToArray(), QueryDashboardQuickFilter.HighVariability => source.Where(x => x.MeanExecutionTime.TotalMilliseconds > 0 && x.ExecutionTimeStandardDeviationMilliseconds / x.MeanExecutionTime.TotalMilliseconds >= thresholds.HighVariability).ToArray(), QueryDashboardQuickFilter.IoHeavy => source.Where(x => x.SharedBlocksRead > 0).OrderByDescending(x => x.SharedBlocksRead).ToArray(), QueryDashboardQuickFilter.TemporaryUsers => source.Where(x => x.TemporaryBlocksWritten >= thresholds.HighTemporaryWrites).ToArray(), QueryDashboardQuickFilter.WalHeavy => source.Where(x => x.WalBytes >= thresholds.HighWalBytes).ToArray(), QueryDashboardQuickFilter.LowCacheHit => source.Where(x => CacheHit(x) is < 80).ToArray(), _ => source.ToArray() }; }
    public static QueryDashboardDelta Delta(QueryStatisticsSnapshot baseline, QueryStatisticsSnapshot current, QueryIdentity identity) { if (baseline.StatisticsResetAt != current.StatisticsResetAt) return new(identity, 0, TimeSpan.Zero, 0, 0, 0, 0, null, false, "Statistics reset metadata changed."); if (!baseline.Queries.TryGetValue(identity, out var old) || !current.Queries.TryGetValue(identity, out var now)) return new(identity, 0, TimeSpan.Zero, 0, 0, 0, 0, null, false, "Statement is missing from one snapshot."); var calls = now.Calls - old.Calls; var time = now.TotalExecutionTime - old.TotalExecutionTime; if (calls < 0 || time < TimeSpan.Zero || now.Rows < old.Rows || now.SharedBlocksRead < old.SharedBlocksRead || now.TemporaryBlocksWritten < old.TemporaryBlocksWritten) return new(identity, 0, TimeSpan.Zero, 0, 0, 0, 0, null, false, "A cumulative counter decreased; the delta is invalid."); return new(identity, calls, time, now.Rows - old.Rows, now.SharedBlocksHit - old.SharedBlocksHit, now.SharedBlocksRead - old.SharedBlocksRead, now.TemporaryBlocksWritten - old.TemporaryBlocksWritten, now.WalBytes - old.WalBytes, true, null); }
    public static QueryDashboardAvailability ExplainAvailability(PgStatStatementsAvailability availability, bool hasResetPermission = false) => availability.State switch { PgStatStatementsState.Available => new(availability, "Aggregated statistics are available. Values are cumulative since the last reset.", hasResetPermission, false), PgStatStatementsState.NotInstalled => new(availability, "Install pg_stat_statements in the database, then recheck availability.", false, false), PgStatStatementsState.NotPreloaded => new(availability, "Add pg_stat_statements to shared_preload_libraries and restart PostgreSQL before rechecking.", false, true), PgStatStatementsState.InsufficientPermissions => new(availability, "The connected role cannot read pg_stat_statements statistics.", false, false), _ => new(availability, "pg_stat_statements is temporarily unavailable or unsupported on this server.", false, false) };
    public static QueryStatisticsResetValidation ValidateReset(QueryDashboardAvailability state, bool confirmed, bool targeted = false) { if (!state.Availability.IsAvailable) return new(false, "unavailable", "Statistics cannot be reset because pg_stat_statements is unavailable."); if (!state.CanReset) return new(false, "permission", "The connected role does not have permission to reset statistics."); if (!confirmed) return new(false, "confirmation-required", targeted ? "Confirm the targeted pg_stat_statements reset." : "Confirm the server-wide pg_stat_statements reset."); return new(true, "allowed", targeted ? "Targeted reset is allowed after confirmation." : "Server-wide reset is allowed after confirmation."); }
    public static string Duration(TimeSpan value) => value.TotalMilliseconds < 1 ? $"{value.TotalMicroseconds:N0} µs" : value.TotalSeconds < 1 ? $"{value.TotalMilliseconds:N2} ms" : value.TotalMinutes < 1 ? $"{value.TotalSeconds:N2} s" : value.ToString("g");
    public static string Bytes(decimal value) => value < 1024 ? $"{value:N0} B" : value < 1024 * 1024 ? $"{value / 1024:N2} KiB" : value < 1024 * 1024 * 1024 ? $"{value / (1024 * 1024):N2} MiB" : $"{value / (1024 * 1024 * 1024):N2} GiB";
    private static double? CacheHit(IEnumerable<QueryStatistics> values) { var hit = values.Sum(x => x.SharedBlocksHit); var read = values.Sum(x => x.SharedBlocksRead); return hit + read == 0 ? null : hit * 100d / (hit + read); }
    private static double? CacheHit(QueryStatistics value) => value.SharedBlocksHit + value.SharedBlocksRead == 0 ? null : value.SharedBlocksHit * 100d / (value.SharedBlocksHit + value.SharedBlocksRead);
}
