using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace PostgreManagementStudio.Application;

public enum QueryExecutionOutcome { Succeeded, Failed, Cancelled }
public enum ExecutionInclusionState { Included, Excluded, WarmUp, KnownAnomaly }
public enum QueryTextStorageMode { FullText, NormalisedText, FingerprintAndPreview, NoText }
public enum BaselineConfidence { Insufficient, Low, Medium, High }
public enum QueryPerformanceClassification { SignificantlyImproved, Improved, WithinExpectedRange, SlowerThanExpected, SignificantlySlower, InsufficientBaseline, Incomparable, Failed, Cancelled }
public sealed record QueryHistoryIdentity(string Fingerprint, string Server, string Database, string CommandType);
public sealed record QueryExecutionSample(Guid Id, QueryHistoryIdentity Identity, DateTimeOffset StartedAt, TimeSpan ClientDuration, TimeSpan? ServerExecutionTime, long? Rows, QueryExecutionOutcome Outcome, ExecutionInclusionState Inclusion = ExecutionInclusionState.Included, string? NormalisedSql = null, string? OriginalSql = null, string? PlanReference = null, bool Pinned = false, int? PostgreSqlMajorVersion = null, string TimingDefinition = "client-observed");
public sealed record BaselineConfiguration(TimeSpan MaximumAge = default, int MaximumSamples = 100, int MinimumSamples = 5, int RecentWindow = 5) { public TimeSpan EffectiveMaximumAge => MaximumAge == default ? TimeSpan.FromDays(30) : MaximumAge; }
public sealed record QueryPerformanceBaseline(int SampleCount, double MedianMilliseconds, double MedianAbsoluteDeviationMilliseconds, double Percentile25Milliseconds, double Percentile75Milliseconds, double Percentile90Milliseconds, double MinimumMilliseconds, double MaximumMilliseconds, BaselineConfidence Confidence, string Explanation);
public sealed record PerformanceThresholds(double ImprovedPercent = 20, double SignificantImprovementPercent = 50, double ImprovedAbsoluteMilliseconds = 50, double SignificantImprovementAbsoluteMilliseconds = 200, double SlowerPercent = 20, double SignificantSlowerPercent = 50, double SlowerAbsoluteMilliseconds = 100, double SignificantSlowerAbsoluteMilliseconds = 500);
public sealed record HistoryCompatibility(bool IsComparable, IReadOnlyList<string> Warnings) { public string Status => IsComparable ? Warnings.Count == 0 ? "Compatible" : "Compatible with warnings" : "Incomparable"; }
public sealed record PerformanceAssessment(QueryPerformanceClassification Classification, double? DifferencePercent, double? DifferenceMilliseconds, string Explanation);
public sealed record HistoryRetentionPolicy(TimeSpan MaximumAge, int MaximumPerQuery, bool PreservePinned = true);

public static class QueryHistoryService
{
    public static QueryHistoryIdentity Identity(string sql, string server, string database, string commandType) => new(PlanComparisonService.QueryFingerprint(sql), server, database, commandType);
    public static QueryPerformanceBaseline Baseline(IEnumerable<QueryExecutionSample> samples, BaselineConfiguration? configuration = null, DateTimeOffset? now = null)
    { configuration ??= new(); var cutoff = (now ?? DateTimeOffset.UtcNow) - configuration.EffectiveMaximumAge; var values = samples.Where(x => x.Outcome == QueryExecutionOutcome.Succeeded && x.Inclusion == ExecutionInclusionState.Included && x.StartedAt >= cutoff).OrderByDescending(x => x.StartedAt).Take(configuration.MaximumSamples).Select(x => x.ClientDuration.TotalMilliseconds).OrderBy(x => x).ToArray(); if (values.Length < configuration.MinimumSamples) return new(values.Length, 0, 0, 0, 0, 0, values.DefaultIfEmpty().Min(), values.DefaultIfEmpty().Max(), values.Length == 0 ? BaselineConfidence.Insufficient : BaselineConfidence.Low, $"Fewer than {configuration.MinimumSamples} comparable successful executions are available."); var median = Percentile(values, 50); var deviations = values.Select(x => Math.Abs(x - median)).OrderBy(x => x).ToArray(); return new(values.Length, median, Percentile(deviations, 50), Percentile(values, 25), Percentile(values, 75), Percentile(values, 90), values[0], values[^1], values.Length >= 20 ? BaselineConfidence.High : BaselineConfidence.Medium, "Baseline uses successful included client-observed durations within the configured local window."); }
    public static PerformanceAssessment Classify(QueryExecutionSample sample, QueryPerformanceBaseline baseline, PerformanceThresholds? thresholds = null) { thresholds ??= new(); if (sample.Outcome == QueryExecutionOutcome.Failed) return new(QueryPerformanceClassification.Failed, null, null, "Execution failed and does not contribute to the baseline."); if (sample.Outcome == QueryExecutionOutcome.Cancelled) return new(QueryPerformanceClassification.Cancelled, null, null, "Execution was cancelled and does not contribute to the baseline."); if (baseline.Confidence == BaselineConfidence.Insufficient || baseline.MedianMilliseconds <= 0) return new(QueryPerformanceClassification.InsufficientBaseline, null, null, baseline.Explanation); var delta = sample.ClientDuration.TotalMilliseconds - baseline.MedianMilliseconds; var percent = delta / baseline.MedianMilliseconds * 100; var strongOutlier = Math.Abs(delta) > Math.Max(3 * baseline.MedianAbsoluteDeviationMilliseconds, baseline.MedianMilliseconds * .5); var classification = percent <= -thresholds.SignificantImprovementPercent && -delta >= thresholds.SignificantImprovementAbsoluteMilliseconds ? QueryPerformanceClassification.SignificantlyImproved : percent <= -thresholds.ImprovedPercent && -delta >= thresholds.ImprovedAbsoluteMilliseconds ? QueryPerformanceClassification.Improved : percent >= thresholds.SignificantSlowerPercent && delta >= thresholds.SignificantSlowerAbsoluteMilliseconds && strongOutlier ? QueryPerformanceClassification.SignificantlySlower : percent >= thresholds.SlowerPercent && delta >= thresholds.SlowerAbsoluteMilliseconds ? QueryPerformanceClassification.SlowerThanExpected : QueryPerformanceClassification.WithinExpectedRange; return new(classification, percent, delta, $"Observed duration differs from the local median by {percent:N1}% ({delta:+0.0;-0.0;0} ms)."); }
    public static HistoryCompatibility CheckCompatibility(QueryExecutionSample a, QueryExecutionSample b) { var warnings = new List<string>(); if (a.Identity.Server != b.Identity.Server) warnings.Add("Server identity changed."); if (a.Identity.Database != b.Identity.Database) warnings.Add("Database changed."); if (a.Identity.Fingerprint != b.Identity.Fingerprint) warnings.Add("Query fingerprint changed."); if (a.Identity.CommandType != b.Identity.CommandType) warnings.Add("Command type changed."); if (a.PostgreSqlMajorVersion != b.PostgreSqlMajorVersion) warnings.Add("PostgreSQL major version changed."); if (a.TimingDefinition != b.TimingDefinition) warnings.Add("Timing definitions differ."); return new(!warnings.Any(x => x is "Server identity changed." or "Database changed." or "Query fingerprint changed." or "Command type changed."), warnings); }
    public static string ApplyPrivacy(QueryExecutionSample sample, QueryTextStorageMode mode) => mode switch { QueryTextStorageMode.FullText => JsonSerializer.Serialize(sample), QueryTextStorageMode.NormalisedText => JsonSerializer.Serialize(sample with { OriginalSql = null }), QueryTextStorageMode.FingerprintAndPreview => JsonSerializer.Serialize(sample with { OriginalSql = null, NormalisedSql = Preview(sample.NormalisedSql) }), QueryTextStorageMode.NoText => JsonSerializer.Serialize(sample with { OriginalSql = null, NormalisedSql = null }), _ => JsonSerializer.Serialize(sample) };
    public static string Redact(string sql) => Regex.Replace(Regex.Replace(sql, @"'(?:''|[^'])*'", "'[redacted]'"), @"\b\d+(?:\.\d+)?\b", "[redacted]");
    public static IReadOnlyList<QueryExecutionSample> Retain(IEnumerable<QueryExecutionSample> samples, HistoryRetentionPolicy policy, DateTimeOffset? now = null) { var cutoff = (now ?? DateTimeOffset.UtcNow) - policy.MaximumAge; return samples.Where(x => x.Pinned || x.StartedAt >= cutoff).GroupBy(x => x.Identity).SelectMany(g => g.OrderByDescending(x => x.StartedAt).Take(policy.MaximumPerQuery).OrderBy(x => x.StartedAt)).ToArray(); }
    public static string ExportMarkdown(IEnumerable<QueryExecutionSample> samples, QueryPerformanceBaseline? baseline = null) { var b = new StringBuilder("# Query Performance History\n\n"); if (baseline is not null) b.AppendLine($"Baseline: {baseline.MedianMilliseconds:N2} ms ({baseline.Confidence})\n"); b.AppendLine("| Timestamp | Database | Duration | Outcome | Inclusion |\n|---|---|---:|---|---|"); foreach (var x in samples.OrderBy(x => x.StartedAt)) b.AppendLine($"| {x.StartedAt:O} | {x.Identity.Database} | {x.ClientDuration.TotalMilliseconds:N2} ms | {x.Outcome} | {x.Inclusion} |"); return b.ToString(); }
    public static double Percentile(IReadOnlyList<double> values, double percentile) { if (values.Count == 0) return 0; var position = (values.Count - 1) * percentile / 100; var lower = (int)Math.Floor(position); var upper = (int)Math.Ceiling(position); return lower == upper ? values[lower] : values[lower] + (values[upper] - values[lower]) * (position - lower); }
    private static string? Preview(string? value) => value is null ? null : value.Length <= 160 ? value : value[..160] + "…";
}
