using System.Security.Cryptography;
using System.Text;

namespace PostgreManagementStudio.Application;

public enum PgStatStatementsState { Available, NotInstalled, NotPreloaded, InsufficientPermissions, Unsupported, TemporarilyUnavailable }
public sealed record PgStatStatementsAvailability(PgStatStatementsState State, string Message, string? SetupCommand = null) { public bool IsAvailable => State == PgStatStatementsState.Available; }
public sealed record QueryStatisticsCapabilities(bool SupportsPlanningMetrics, bool SupportsWalMetrics, bool SupportsJitMetrics, bool SupportsTopLevelFlag, bool SupportsStatisticsResetTime);
public sealed record QueryIdentity(string Server, string Database, string User, long QueryId, string? FallbackKey = null)
{ public string StableKey => QueryId != 0 ? $"{Server}|{Database}|{User}|{QueryId}" : $"{Server}|{Database}|{User}|fallback:{FallbackKey}"; }
public sealed record QueryStatistics(QueryIdentity Identity, string QueryText, long Calls, TimeSpan TotalExecutionTime, TimeSpan MeanExecutionTime, TimeSpan MinimumExecutionTime, TimeSpan MaximumExecutionTime, double ExecutionTimeStandardDeviationMilliseconds, long Rows, long SharedBlocksHit, long SharedBlocksRead, long TemporaryBlocksWritten, decimal? WalBytes = null, TimeSpan? TotalPlanningTime = null);
public sealed record QueryStatisticsSnapshot(DateTimeOffset CapturedAt, DateTimeOffset? StatisticsResetAt, string Server, string Database, string User, IReadOnlyDictionary<QueryIdentity, QueryStatistics> Queries, QueryStatisticsCapabilities Capabilities);
public sealed record QueryIntervalStatistics(QueryIdentity Identity, TimeSpan Interval, long Calls, TimeSpan ExecutionTime, TimeSpan? MeanExecutionTime, double? CallsPerSecond, double? ExecutionMillisecondsPerSecond, bool IsComparable, string? NonComparableReason);
public enum QueryRanking { TotalTime, MeanTime, Calls, MaximumTime, Variability, Rows, SharedReads, TemporaryWrites, WalBytes, PlanningTime }
public enum QueryStatementType { Select, Insert, Update, Delete, Merge, Ddl, TransactionControl, Maintenance, Utility, Other }
public sealed record QueryPerformanceFilter(string? Database = null, string? User = null, long? QueryId = null, string? QueryText = null, long? MinimumCalls = null, TimeSpan? MinimumTotalTime = null, TimeSpan? MinimumMeanTime = null, bool ExcludeUtility = false, bool OnlyChanged = false);
public enum RegressionStatus { Improved, Stable, PossibleRegression, SignificantRegression, InsufficientData, NotComparable }
public sealed record QueryRegressionResult(RegressionStatus Status, double? MeanChangePercent, string Explanation);

public static class QueryPerformanceService
{
    public static QueryIdentity Identity(string server, string database, string user, long queryId, string queryText) => queryId != 0 ? new(server, database, user, queryId) : new(server, database, user, 0, Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(queryText))).ToLowerInvariant());
    public static QueryStatementType Classify(string sql)
    { var text = StripComments(sql).TrimStart(); if (text.StartsWith("WITH ", StringComparison.OrdinalIgnoreCase)) { var match = System.Text.RegularExpressions.Regex.Match(text, "\\b(SELECT|INSERT|UPDATE|DELETE|MERGE)\\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase); if (match.Success) text = match.Value; } var word = text.Split(new[] { ' ', '\r', '\n', '\t', '(' }, StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()?.ToUpperInvariant(); return word switch { "SELECT" => QueryStatementType.Select, "INSERT" => QueryStatementType.Insert, "UPDATE" => QueryStatementType.Update, "DELETE" => QueryStatementType.Delete, "MERGE" => QueryStatementType.Merge, "BEGIN" or "COMMIT" or "ROLLBACK" or "SAVEPOINT" => QueryStatementType.TransactionControl, "VACUUM" or "ANALYZE" or "REINDEX" or "CLUSTER" => QueryStatementType.Maintenance, "CREATE" or "ALTER" or "DROP" or "TRUNCATE" => QueryStatementType.Ddl, "SET" or "SHOW" or "EXPLAIN" or "GRANT" or "REVOKE" => QueryStatementType.Utility, _ => QueryStatementType.Other }; }
    public static IReadOnlyList<QueryStatistics> Rank(IEnumerable<QueryStatistics> queries, QueryRanking ranking, QueryPerformanceFilter? filter = null) { filter ??= new(); return queries.Where(x => (filter.Database is null || x.Identity.Database == filter.Database) && (filter.User is null || x.Identity.User == filter.User) && (filter.QueryId is null || x.Identity.QueryId == filter.QueryId) && (filter.QueryText is null || x.QueryText.Contains(filter.QueryText, StringComparison.OrdinalIgnoreCase)) && (filter.MinimumCalls is null || x.Calls >= filter.MinimumCalls) && (filter.MinimumTotalTime is null || x.TotalExecutionTime >= filter.MinimumTotalTime) && (filter.MinimumMeanTime is null || x.MeanExecutionTime >= filter.MinimumMeanTime) && (!filter.ExcludeUtility || Classify(x.QueryText) != QueryStatementType.Utility)).OrderByDescending(x => Metric(x, ranking)).ThenByDescending(x => x.Calls).ThenBy(x => x.Identity.StableKey, StringComparer.Ordinal).ToArray(); }
    public static QueryIntervalStatistics Compare(QueryStatisticsSnapshot previous, QueryStatisticsSnapshot current, QueryIdentity identity)
    { if (previous.StatisticsResetAt != current.StatisticsResetAt) return new(identity, current.CapturedAt - previous.CapturedAt, 0, TimeSpan.Zero, null, null, null, false, "pg_stat_statements statistics were reset between captures."); if (!previous.Queries.TryGetValue(identity, out var old) || !current.Queries.TryGetValue(identity, out var now)) return new(identity, current.CapturedAt - previous.CapturedAt, 0, TimeSpan.Zero, null, null, null, false, "The query was missing from one snapshot."); var calls = now.Calls - old.Calls; var execution = now.TotalExecutionTime - old.TotalExecutionTime; var interval = current.CapturedAt - previous.CapturedAt; if (calls < 0 || execution < TimeSpan.Zero || interval <= TimeSpan.Zero) return new(identity, interval, 0, TimeSpan.Zero, null, null, null, false, "Counters decreased or the sample interval is invalid."); return new(identity, interval, calls, execution, calls == 0 ? null : execution / calls, calls / interval.TotalSeconds, execution.TotalMilliseconds / interval.TotalSeconds, true, null); }
    public static QueryRegressionResult DetectRegression(QueryIntervalStatistics previous, QueryIntervalStatistics current, int minimumCalls = 10, TimeSpan? minimumMean = null, double increase = 0.5, TimeSpan? minimumExecutionDelta = null)
    { minimumMean ??= TimeSpan.FromMilliseconds(5); minimumExecutionDelta ??= TimeSpan.FromSeconds(1); if (!previous.IsComparable || !current.IsComparable) return new(RegressionStatus.NotComparable, null, previous.NonComparableReason ?? current.NonComparableReason ?? "Samples cannot be compared."); if (previous.Calls < minimumCalls || current.Calls < minimumCalls || previous.MeanExecutionTime < minimumMean || current.MeanExecutionTime is null) return new(RegressionStatus.InsufficientData, null, "There are not enough calls or execution time to classify this change."); var change = (current.MeanExecutionTime!.Value - previous.MeanExecutionTime!.Value).TotalMilliseconds / previous.MeanExecutionTime.Value.TotalMilliseconds; var delta = current.ExecutionTime - previous.ExecutionTime; if (change >= increase && delta >= minimumExecutionDelta) return new(RegressionStatus.SignificantRegression, change * 100, $"Mean execution time increased by {change:P1}; interval execution time increased by {delta:g}."); if (change >= increase) return new(RegressionStatus.PossibleRegression, change * 100, $"Mean execution time increased by {change:P1}, but the interval workload was small."); return new(change < -increase ? RegressionStatus.Improved : RegressionStatus.Stable, change * 100, $"Mean execution time changed by {change:P1}."); }
    private static decimal Metric(QueryStatistics x, QueryRanking r) => r switch { QueryRanking.TotalTime => (decimal)x.TotalExecutionTime.Ticks, QueryRanking.MeanTime => (decimal)x.MeanExecutionTime.Ticks, QueryRanking.Calls => x.Calls, QueryRanking.MaximumTime => (decimal)x.MaximumExecutionTime.Ticks, QueryRanking.Variability => (decimal)x.ExecutionTimeStandardDeviationMilliseconds, QueryRanking.Rows => x.Rows, QueryRanking.SharedReads => x.SharedBlocksRead, QueryRanking.TemporaryWrites => x.TemporaryBlocksWritten, QueryRanking.WalBytes => x.WalBytes ?? 0, QueryRanking.PlanningTime => (decimal)(x.TotalPlanningTime?.Ticks ?? 0), _ => 0 };
    private static string StripComments(string value) => System.Text.RegularExpressions.Regex.Replace(System.Text.RegularExpressions.Regex.Replace(value, @"/\*.*?\*/", "", System.Text.RegularExpressions.RegexOptions.Singleline), @"--[^\r\n]*", "");
}

public sealed class QuerySnapshotHistory(int maximumSnapshots = 60)
{ private readonly LinkedList<QueryStatisticsSnapshot> _items = new(); public IReadOnlyList<QueryStatisticsSnapshot> Snapshots => _items.ToArray(); public void Add(QueryStatisticsSnapshot value) { _items.AddLast(value); while (_items.Count > Math.Max(1, maximumSnapshots)) _items.RemoveFirst(); } public void Clear() => _items.Clear(); }
public static class QueryExplainTemplateService
{ public static string Generate(string normalizedSql, bool analyze = false) { var statement = normalizedSql.Trim(); var type = QueryPerformanceService.Classify(statement); var warning = analyze && type is QueryStatementType.Insert or QueryStatementType.Update or QueryStatementType.Delete or QueryStatementType.Merge ? "-- WARNING: EXPLAIN ANALYZE executes this statement and may modify data or trigger side effects.\n" : ""; return warning + $"EXPLAIN ({(analyze ? "ANALYZE, " : "")}VERBOSE, SETTINGS, FORMAT TEXT)\n{statement.TrimEnd(';')};"; } }
