using System.Text;
using System.Text.Json;

namespace PostgreManagementStudio.Application;

public sealed record ActivityFilter(string? Database = null, string? User = null, string? ApplicationName = null, string? ClientAddress = null, string? BackendType = null, BackendState? State = null, string? WaitEventType = null, string? QueryText = null, int? ProcessId = null, TimeSpan? MinimumDuration = null, bool? Blocked = null)
{ public bool Matches(BackendSession s) => (Database is null || s.Database == Database) && (User is null || s.User == User) && (ApplicationName is null || s.ApplicationName == ApplicationName) && (ClientAddress is null || s.ClientAddress == ClientAddress) && (BackendType is null || s.BackendType == BackendType) && (State is null || s.ClassifiedState == State) && (WaitEventType is null || s.WaitEventType == WaitEventType) && (QueryText is null || (s.Query?.Contains(QueryText, StringComparison.OrdinalIgnoreCase) ?? false)) && (ProcessId is null || s.ProcessId == ProcessId) && (MinimumDuration is null || s.Duration >= MinimumDuration) && (Blocked is null || s.Blocked == Blocked); }
public sealed record ActivitySample(DateTimeOffset Timestamp, int Active, int Idle, int IdleInTransaction, int Waiting, int Blocked, int LongRunning, int TotalConnections);
public sealed class ActivitySampleHistory(TimeSpan? retention = null)
{ private readonly TimeSpan _retention = retention ?? TimeSpan.FromMinutes(15); private readonly LinkedList<ActivitySample> _samples = new(); public IReadOnlyList<ActivitySample> Samples => _samples.ToArray(); public void Add(ActivitySample sample) { _samples.AddLast(sample); var cutoff = sample.Timestamp - _retention; while (_samples.First is not null && _samples.First.Value.Timestamp < cutoff) _samples.RemoveFirst(); } public void Clear() => _samples.Clear(); public string ToCsv() => "Timestamp,Active,Idle,IdleInTransaction,Waiting,Blocked,LongRunning,TotalConnections\r\n" + string.Join(Environment.NewLine, _samples.Select(x => string.Join(',', x.Timestamp.ToString("O"), x.Active, x.Idle, x.IdleInTransaction, x.Waiting, x.Blocked, x.LongRunning, x.TotalConnections))); }
public sealed record SessionIdentity(int ProcessId, DateTimeOffset? BackendStart, string? Database, string? User, string? ApplicationName);
public sealed record SessionActionResult(string Action, int ProcessId, bool Accepted, string Code, string Message);
public sealed record SessionActionHistoryEntry(DateTimeOffset Timestamp, string Action, string Server, string? Database, int ProcessId, string? User, string? ApplicationName, string QueryPreview, bool Accepted, string Code, string Message);
public sealed class SessionActionHistory(int maximumEntries = 100)
{ private readonly LinkedList<SessionActionHistoryEntry> _entries = new(); public IReadOnlyList<SessionActionHistoryEntry> Entries => _entries.ToArray(); public void Add(SessionActionHistoryEntry entry) { _entries.AddFirst(entry with { QueryPreview = entry.QueryPreview.Length > 240 ? entry.QueryPreview[..240] : entry.QueryPreview }); while (_entries.Count > Math.Max(1, maximumEntries)) _entries.RemoveLast(); } public void Clear() => _entries.Clear(); }
public static class SessionActionSafety
{
    public static bool IdentityMatches(SessionIdentity expected, BackendSession current) => expected.ProcessId == current.ProcessId && expected.BackendStart == current.BackendStart && expected.Database == current.Database && expected.User == current.User && expected.ApplicationName == current.ApplicationName;
    public static BackendActionResult Validate(BackendSession target, int currentPid, int? monitorPid, bool terminating) { var safety = BackendSafety.ValidateTermination(target, currentPid, monitorPid, null); if (!terminating && target.ProcessId == currentPid) return new(false, "self", "Cannot cancel the current application session."); return safety; }
}
public static class ActivityCapacityService
{ public static (double UsagePercent, string Severity) Classify(int current, int max) { if (max <= 0) return (0, "Unavailable"); var p = 100d * current / max; return (p, p >= 95 ? "Critical" : p >= 85 ? "High" : p >= 70 ? "Elevated" : "Normal"); } }
public static class ActivityExportServiceV2
{ public static string ToMarkdown(IEnumerable<BackendSession> sessions, bool includeQueryText = false) { var rows = sessions.Select(s => $"| {s.ProcessId} | {s.Database} | {s.User} | {s.ClassifiedState} | {s.Duration:g} | {(includeQueryText && !s.QueryUnavailable ? Escape(s.Query) : "[redacted]")} |"); return "| PID | Database | User | State | Duration | Query |\n|---:|---|---|---|---:|---|\n" + string.Join(Environment.NewLine, rows); } public static string ToJson(IEnumerable<BackendSession> sessions, bool includeQueryText = false) => JsonSerializer.Serialize(sessions.Select(s => new { s.ProcessId, s.Database, s.User, s.ApplicationName, s.State, s.Blocked, s.Duration, Query = includeQueryText && !s.QueryUnavailable ? s.Query : "[redacted]" })); private static string Escape(string? value) => (value ?? "").Replace("|", "\\|").Replace("\r", " ").Replace("\n", " "); }
