using System.Text;
using System.Text.Json;

namespace PostgreManagementStudio.Application;

public enum QueryTextDisplayMode { Show, MaskLiterals, Hide }
public sealed record SessionMonitorThresholds(TimeSpan LongQuery = default, TimeSpan WarningQuery = default, TimeSpan HighQuery = default, TimeSpan LongTransaction = default) { public TimeSpan EffectiveLongQuery => LongQuery == default ? TimeSpan.FromSeconds(30) : LongQuery; public TimeSpan EffectiveWarningQuery => WarningQuery == default ? TimeSpan.FromMinutes(2) : WarningQuery; public TimeSpan EffectiveHighQuery => HighQuery == default ? TimeSpan.FromMinutes(10) : HighQuery; public TimeSpan EffectiveLongTransaction => LongTransaction == default ? TimeSpan.FromMinutes(5) : LongTransaction; }
public sealed record SessionMonitorFilter(string? Database = null, string? User = null, string? Application = null, BackendState? State = null, string? WaitEventType = null, TimeSpan? MinimumQueryDuration = null, TimeSpan? MinimumTransactionDuration = null, string? QueryText = null, bool? Blocked = null, bool? Blocking = null, bool ExcludeBackground = false, bool ExcludeMonitoring = true)
{ public bool Matches(BackendSession s, SessionMonitorThresholds? thresholds = null) { thresholds ??= new(); return (Database is null || s.Database == Database) && (User is null || s.User == User) && (Application is null || s.ApplicationName == Application) && (State is null || s.ClassifiedState == State) && (WaitEventType is null || s.WaitEventType == WaitEventType) && (MinimumQueryDuration is null || s.Duration >= MinimumQueryDuration) && (MinimumTransactionDuration is null || s.TransactionDuration >= MinimumTransactionDuration) && (QueryText is null || (s.Query?.Contains(QueryText, StringComparison.OrdinalIgnoreCase) ?? false)) && (Blocked is null || s.Blocked == Blocked) && (Blocking is null || (s.BlockingCount > 0) == Blocking) && (!ExcludeBackground || s.ClassifiedState != BackendState.BackgroundWorker) && (!ExcludeMonitoring || !s.IsMonitoringSession); } }
public sealed record SessionFilterPreset(string Name, SessionMonitorFilter Filter, int RefreshSeconds = 5, bool ShowBackground = false);
public enum SessionDiagnosticSeverity { Information, Warning, High }
public sealed record SessionDiagnostic(SessionDiagnosticSeverity Severity, int ProcessId, string Summary, string Evidence, string Rule);
public sealed record LockSummary(int Held, int Awaited, int Granted, int Unresolved, int RelationLocks, int TransactionLocks, int AdvisoryLocks);
public sealed record SessionSnapshotComparison(IReadOnlyList<int> NewSessions, IReadOnlyList<int> EndedSessions, IReadOnlyList<int> StateChanged, IReadOnlyList<int> NewBlockers, IReadOnlyList<int> ResolvedBlockers);
public sealed record SessionActionAudit(DateTimeOffset Timestamp, string Server, string Database, string ActingUser, int TargetPid, DateTimeOffset? TargetBackendStart, string Action, bool Confirmed, bool Accepted, string Code, string QueryPreview);

public static class SessionMonitorService
{
    public static IReadOnlyList<SessionDiagnostic> Diagnose(ActivitySnapshot snapshot, SessionMonitorThresholds? thresholds = null)
    { thresholds ??= new(); var result = new List<SessionDiagnostic>(); foreach (var s in snapshot.Sessions) { if (s.State == "active" && s.Duration >= thresholds.EffectiveLongQuery) { var severity = s.Duration >= thresholds.EffectiveHighQuery ? SessionDiagnosticSeverity.High : s.Duration >= thresholds.EffectiveWarningQuery ? SessionDiagnosticSeverity.Warning : SessionDiagnosticSeverity.Information; result.Add(new(severity, s.ProcessId, $"Query has been active for {s.Duration:g}.", $"PID {s.ProcessId}; wait={s.WaitEventType ?? "none"}/{s.WaitEvent ?? "none"}; blocked={s.Blocked}.", "long-running-query")); } if (s.ClassifiedState is BackendState.IdleInTransaction or BackendState.IdleInTransactionAborted && s.TransactionDuration >= thresholds.EffectiveLongTransaction) result.Add(new(SessionDiagnosticSeverity.Warning, s.ProcessId, "Session has a long-running idle transaction.", $"Transaction age {s.TransactionDuration:g}; blocked sessions={s.BlockingCount}.", "idle-in-transaction")); if (s.Blocked) result.Add(new(SessionDiagnosticSeverity.Warning, s.ProcessId, "Session is blocked by another backend.", $"Direct blocker count={s.BlockingCount}.", "blocked-session")); if (s.BlockingCount > 1) result.Add(new(SessionDiagnosticSeverity.Warning, s.ProcessId, "Session is blocking multiple backends.", $"Blocking count={s.BlockingCount}.", "blocking-session")); if (s.QueryUnavailable) result.Add(new(SessionDiagnosticSeverity.Information, s.ProcessId, "Query text is unavailable due to PostgreSQL visibility limits.", "The connected role cannot see the complete query text.", "limited-query-visibility")); } return result.OrderByDescending(x => x.Severity).ThenBy(x => x.ProcessId).ToArray(); }
    public static LockSummary SummarizeLocks(IEnumerable<BackendLock> locks, int pid) { var selected = locks.Where(x => x.ProcessId == pid).ToArray(); return new(selected.Count(x => x.Granted), selected.Count(x => !x.Granted), selected.Count(x => x.Granted), selected.Count(x => x.Relation is null), selected.Count(x => x.LockType?.Contains("relation", StringComparison.OrdinalIgnoreCase) == true), selected.Count(x => x.LockType?.Contains("transaction", StringComparison.OrdinalIgnoreCase) == true), selected.Count(x => x.LockType?.Contains("advisory", StringComparison.OrdinalIgnoreCase) == true)); }
    public static string QueryPreview(string? query, QueryTextDisplayMode mode, int maxLength = 240) { if (mode == QueryTextDisplayMode.Hide || query is null) return "[query text hidden]"; var value = mode == QueryTextDisplayMode.MaskLiterals ? QueryHistoryService.Redact(query) : query; return value.Length <= maxLength ? value : value[..maxLength] + "… [truncated]"; }
    public static string SaveSnapshot(ActivitySnapshot snapshot, QueryTextDisplayMode privacy = QueryTextDisplayMode.Show) => JsonSerializer.Serialize(new { SchemaVersion = 1, snapshot.Sequence, snapshot.ServerTime, Sessions = snapshot.Sessions.Select(x => new { x.ProcessId, x.Database, x.User, x.ApplicationName, x.State, x.Duration, x.Blocked, Query = QueryPreview(x.Query, privacy), x.QueryUnavailable }), snapshot.Blocking, snapshot.Locks, snapshot.Summary }, new JsonSerializerOptions { WriteIndented = true });
    public static SessionSnapshotComparison Compare(ActivitySnapshot before, ActivitySnapshot after) { var old = before.Sessions.ToDictionary(x => x.ProcessId); var current = after.Sessions.ToDictionary(x => x.ProcessId); return new(current.Keys.Except(old.Keys).OrderBy(x => x).ToArray(), old.Keys.Except(current.Keys).OrderBy(x => x).ToArray(), current.Keys.Intersect(old.Keys).Where(x => current[x].State != old[x].State).OrderBy(x => x).ToArray(), after.Blocking.Select(x => x.BlockingProcessId).Except(before.Blocking.Select(x => x.BlockingProcessId)).OrderBy(x => x).ToArray(), before.Blocking.Select(x => x.BlockingProcessId).Except(after.Blocking.Select(x => x.BlockingProcessId)).OrderBy(x => x).ToArray()); }
    public static string ExportCsv(IEnumerable<BackendSession> sessions, QueryTextDisplayMode privacy = QueryTextDisplayMode.Hide) { var b = new StringBuilder("PID,Database,User,State,Duration,Blocked,Query\r\n"); foreach (var s in sessions) b.AppendLine(string.Join(',', s.ProcessId, Csv(s.Database), Csv(s.User), Csv(s.ClassifiedState.ToString()), s.Duration.TotalSeconds.ToString("F1"), s.Blocked, Csv(QueryPreview(s.Query, privacy)))); return b.ToString(); }
    private static string Csv(string? value) => '"' + (value ?? "").Replace("\"", "\"\"").Replace("\r", " ").Replace("\n", " ") + '"';
}
