/*
Sprint 61 generated SQL evidence
Candidate: 424133bff9684c962b93a71feab3ebdc49da46bd

The SELECT below was generated by the packaged Object Explorer and executed
successfully against PostgreSQL 18.4. The remaining safety shapes are asserted
by the two-pass ObjectScripting unit/integration suites. Exact catalogue object
replay is performed by ObjectScriptingIntegrationTests.
*/

SELECT
    "order_id",
    "customer_id",
    "order_code",
    "amount",
    "state",
    "tags",
    "payload",
    "created_at",
    "updated_at",
    "calculated_total"
FROM "s61_audit"."orders"
LIMIT 10000;

/*
Required safety properties verified by tests:

- INSERT excludes generated and identity-always columns and columns whose
  defaults should be allowed to apply.
- UPDATE includes a primary-key-shaped WHERE predicate where available and is
  never unconditional.
- DELETE includes a primary-key-shaped WHERE predicate where available and is
  never unconditional.
- DROP is schema-qualified, terminated, and never silently includes CASCADE.
- hostile and mixed-case identifiers remain one quoted PostgreSQL identifier.

Replay tests:

- SeededTableProducesExecutableCreateAndSafeTemplates
- SupportedCatalogueObjectsProduceFidelityScriptsAndSequenceRoundTrips
- RenameAndDropRecreateUseOidIdentityAndRoutineOverloadsRemainDistinct
- HostileIdentifier_RemainsOneQuotedObjectAndMetadataIsInert
*/
