\set ON_ERROR_STOP on

SET ROLE :"app_role";
CREATE SCHEMA "PMS Regression";

CREATE TABLE "PMS Regression"."Type Matrix" (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nullable_text text NULL,
    unicode_text text NOT NULL,
    large_text text NOT NULL,
    binary_value bytea NOT NULL,
    numeric_value numeric(30,12) NOT NULL,
    boolean_value boolean NOT NULL,
    date_value date NOT NULL,
    timestamp_value timestamp NOT NULL,
    timestamptz_value timestamptz NOT NULL,
    interval_value interval NOT NULL,
    uuid_value uuid NOT NULL,
    json_value json NOT NULL,
    jsonb_value jsonb NOT NULL,
    integer_array integer[] NOT NULL,
    generated_value integer GENERATED ALWAYS AS (id * 2) STORED,
    CONSTRAINT uq_type_matrix_unicode UNIQUE (unicode_text)
);

INSERT INTO "PMS Regression"."Type Matrix" (
    nullable_text, unicode_text, large_text, binary_value, numeric_value,
    boolean_value, date_value, timestamp_value, timestamptz_value,
    interval_value, uuid_value, json_value, jsonb_value, integer_array
) VALUES (
    NULL, 'Résumé 東京 🚀', repeat('x', 8192), decode('00ff10', 'hex'),
    123456789012345678.123456789012, TRUE, DATE '2024-02-29',
    TIMESTAMP '2024-02-29 23:59:58.123456',
    TIMESTAMPTZ '2024-02-29 21:59:58.123456+00',
    INTERVAL '2 days 03:04:05.678', '12345678-1234-5678-9abc-123456789abc',
    '{"kind":"json","value":1}', '{"kind":"jsonb","nested":{"value":2}}',
    ARRAY[1,2,3]
);

CREATE TABLE "PMS Regression"."Parent Table" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE
);

CREATE TABLE "PMS Regression"."Child Table" (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_id integer NOT NULL REFERENCES "PMS Regression"."Parent Table"(id),
    note text
);

CREATE INDEX "Index With Space" ON "PMS Regression"."Child Table"(parent_id);
CREATE VIEW "PMS Regression"."Order" AS SELECT id, unicode_text FROM "PMS Regression"."Type Matrix";
CREATE MATERIALIZED VIEW "PMS Regression"."Materialized Résumé" AS SELECT count(*) AS row_count FROM "PMS Regression"."Type Matrix";
CREATE MATERIALIZED VIEW "PMS Regression"."Materialized Empty" AS SELECT count(*) AS row_count FROM "PMS Regression"."Type Matrix" WITH NO DATA;
CREATE SEQUENCE "PMS Regression"."Mixed Case Sequence";
CREATE TYPE "PMS Regression"."Status Type" AS ENUM ('new', 'done');
CREATE FUNCTION "PMS Regression"."Function With Space"(value integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT value + 1 $$;
CREATE PROCEDURE "PMS Regression"."Procedure With Space"() LANGUAGE plpgsql AS $$ BEGIN NULL; END $$;
CREATE TABLE "PMS Regression"."Partitioned Table" (id integer, created_on date) PARTITION BY RANGE (created_on);
CREATE TABLE "PMS Regression"."Partition 2024" PARTITION OF "PMS Regression"."Partitioned Table" FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
CREATE INDEX "Partitioned Parent Index" ON "PMS Regression"."Partitioned Table"(id);
CREATE FUNCTION "PMS Regression".pms_partition_trigger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
CREATE TRIGGER pms_partition_trigger BEFORE INSERT ON "PMS Regression"."Partitioned Table"
    FOR EACH ROW EXECUTE FUNCTION "PMS Regression".pms_partition_trigger();
CREATE TABLE "PMS Regression"."Inherited Parent" (inherited_id integer NOT NULL);
CREATE TABLE "PMS Regression"."Inherited Child" (local_value text) INHERITS ("PMS Regression"."Inherited Parent");

GRANT CONNECT ON DATABASE :"test_database" TO :"readonly_role", :"restricted_role";
GRANT USAGE ON SCHEMA "PMS Regression" TO :"readonly_role";
GRANT SELECT ON ALL TABLES IN SCHEMA "PMS Regression" TO :"readonly_role";
REVOKE ALL ON SCHEMA "PMS Regression" FROM :"restricted_role";
RESET ROLE;
